Update changelog for 8.7 release
elastic/apm-server pull request #10186
Opened 2023-02-07 13:40 UTC by lahsivjar

Updated changelogs for 8.7 release.

2023-02-07 13:44 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10186/detail/PR-10186/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10186/detail/PR-10186/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10186/detail/PR-10186/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10186/detail/PR-10186/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_10186.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2023-02-07T13:30:42.100Z&rangeTo=2023-02-07T13:50:42.100Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b168012ff92d33651f3959712dca97af&transactionId=66dc2ef43b8eeb2c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-02-07T13:40:42.100+0000


* Duration: 3 min 30 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-02-08 02:39 UTC, lahsivjar commented
I have combined entries for similar features on different aggregators in a single entry as well as moved some of the changelog entries so that the numerous changes to the aggregations are together. Let me know if others have any concerns/thoughts about this.

2023-02-08 03:07 UTC, axw approved these changes

2023-02-08 03:07 UTC, axw commented on changelogs/8.7.asciidoc
> +- Use Elasticsearch fetcher for agent remote configuration where possible {pull}9720[9720] {pull}10088[10088]
@lahsivjar could you please add a changelog entry for https://github.com/elastic/apm-server/pull/9722?

@kruskall please try to remember to add changelog entries for major changes like this in the future

2023-02-08 03:35 UTC, bmorelli25 requested changes
Can you please add `* <<release-notes-8.7>>` above this line:

https://github.com/elastic/apm-server/blame/3a12640024314ef3aa313708fcd34702f79ca6ba/docs/release-notes.asciidoc#L12

2023-02-08 03:37 UTC, bmorelli25 commented on changelogs/8.7.asciidoc
> +==== Deprecations
Let's remove this heading since there aren't any deprecations

```suggestion
```

2023-02-08 10:14 UTC, lahsivjar commented
@bmorelli25 I have updated the PR with the suggested changes. Merging this, let me know if there are any other changes, I will create a separate PR.

2023-02-08 10:14 UTC, merged