Add support for mobile UI filtering
elastic/apm-server pull request #10697
Opened 2023-04-25 17:36 UTC by bryce-b

## Motivation/summary
The mobile ui wants to filter data based on host.os.version & service.version. Http spans are a key part of the mobile ui, and when filters are added for either of these attributes all http related charts will be empty.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

## Related issues

https://github.com/elastic/apm-agent-ios/issues/145

2023-04-25 17:43 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10697/detail/PR-10697/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10697/detail/PR-10697/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10697/detail/PR-10697/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-10697/detail/PR-10697/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_10697.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2023-04-25T17:27:12.380Z&rangeTo=2023-04-25T17:47:12.380Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=ae756c97335bd391c3532e0e7bde3077&transactionId=55130b5ad05a4e0f)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2023-04-25T17:37:12.380+0000


* Duration: 6 min 46 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2023-04-25 17:43 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
goos: linux
goarch: amd64
pkg: github.com/elastic/apm-server/internal/agentcfg
cpu: 12th Gen Intel(R) Core(TM) i5-12500
                                  │ build/main/bench.out │              bench.out              │
                                  │        sec/op        │    sec/op     vs base               │
FetchAndAdd/FetchFromCache-12                41.12n ± 0%    46.11n ± 0%  +12.16% (p=0.002 n=6)
FetchAndAdd/FetchAndAddToCache-12            91.67n ± 6%   103.85n ± 3%  +13.29% (p=0.002 n=6)
geomean                                      61.39n         69.20n       +12.72%

                                  │ build/main/bench.out │             bench.out              │
                                  │         B/op         │    B/op     vs base                │
geomean                                                ²               +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                                  │ build/main/bench.out │             bench.out              │
                                  │      allocs/op       │ allocs/op   vs base                │
geomean                                                ²               +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

pkg: github.com/elastic/apm-server/internal/beater/request
                                             │ build/main/bench.out │              bench.out              │
                                             │        sec/op        │    sec/op     vs base               │
ContextReset/X-Real-IP_ipv6-12                         838.6n ±  9%   679.5n ± 27%  -18.98% (p=0.004 n=6)
ContextResetContentEncoding/empty-12                   120.4n ±  1%   133.8n ±  1%  +11.08% (p=0.002 n=6)
ContextResetContentEncoding/uncompressed-12            142.0n ±  1%   160.4n ±  1%  +12.96% (p=0.002 n=6)
geomean                                                914.3n         894.1n         -2.21%

                                             │ build/main/bench.out │              bench.out               │
                                             │         B/op         │     B/op      vs base                │
geomean                                                           ²                 +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                                             │ build/main/bench.out │             bench.out              │
                                             │      allocs/op       │ allocs/op   vs base                │
geomean                                                           ²               +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

pkg: github.com/elastic/apm-server/internal/publish
             │ build/main/bench.out │          bench.out          │
             │        sec/op        │   sec/op    vs base         │

             │ build/main/bench.out │           bench.out            │
             │         B/op         │     B/op       vs base         │

             │ build/main/bench.out │           bench.out           │
             │      allocs/op       │  allocs/op    vs base         │

pkg: github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics
                 │ build/main/bench.out │          bench.out           │
                 │        sec/op        │   sec/op     vs base         │

                 │ build/main/bench.out │            bench.out            │
                 │         B/op         │     B/op      vs base           │
¹ all samples are equal

                 │ build/main/bench.out │           bench.out           │
                 │      allocs/op       │ allocs/op   vs base           │
¹ all samples are equal

pkg: github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics
                        │ build/main/bench.out │          bench.out           │
                        │        sec/op        │   sec/op     vs base         │

                        │ build/main/bench.out │           bench.out           │
                        │         B/op         │    B/op     vs base           │
¹ all samples are equal

                        │ build/main/bench.out │           bench.out           │
                        │      allocs/op       │ allocs/op   vs base           │
¹ all samples are equal

pkg: github.com/elastic/apm-server/x-pack/apm-server/sampling
               │ build/main/bench.out │             bench.out              │
               │        sec/op        │    sec/op     vs base              │
geomean                  595.0n         625.3n        +5.08%

               │ build/main/bench.out │              bench.out               │
               │         B/op         │     B/op      vs base                │
geomean                             ²                 +0.46%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

               │ build/main/bench.out │             bench.out              │
               │      allocs/op       │ allocs/op   vs base                │
geomean                             ²               +0.00%               ²
¹ all samples are equal
² summaries must be >0 to compute geomean

pkg: github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage
                                            │ build/main/bench.out │               bench.out               │
                                            │        sec/op        │    sec/op      vs base                │
WriteTransaction/json_codec-12                       4.150µ ±   3%   10.631µ ± 68%  +156.17% (p=0.002 n=6)
WriteTransaction/json_codec_big_tx-12                4.944µ ±   5%   15.048µ ± 44%  +204.33% (p=0.002 n=6)
ReadEvents/json_codec/0_events-12                    313.1n ±   9%    346.9n ± 10%   +10.83% (p=0.009 n=6)
ReadEvents/json_codec/1_events-12                    10.70µ ±   5%    11.35µ ±  5%    +6.07% (p=0.015 n=6)
ReadEvents/json_codec_big_tx/0_events-12             315.8n ±   8%    352.9n ±  8%   +11.71% (p=0.015 n=6)
ReadEvents/json_codec_big_tx/1_events-12             12.05µ ±   5%    12.45µ ±  6%    +3.31% (p=0.009 n=6)
ReadEvents/nop_codec/0_events-12                     304.8n ±  15%    346.3n ±  6%   +13.65% (p=0.026 n=6)
ReadEvents/nop_codec_big_tx/0_events-12              312.2n ±   7%    346.5n ±  6%   +11.02% (p=0.002 n=6)
IsTraceSampled/sampled-12                            68.36n ±   1%    76.70n ±  4%   +12.21% (p=0.002 n=6)
IsTraceSampled/unsampled-12                          69.07n ±   2%    77.52n ±  1%   +12.23% (p=0.002 n=6)
IsTraceSampled/unknown-12                            378.6n ±   3%    419.8n ±  6%   +10.90% (p=0.002 n=6)
geomean                                              29.47µ           31.73µ          +7.66%

                                            │ build/main/bench.out │               bench.out                │
                                            │         B/op         │      B/op       vs base                │
ReadEvents/nop_codec/1_events-12                     3.196Ki ±  0%    3.191Ki ±  0%  -0.14% (p=0.009 n=6)
ReadEvents/nop_codec_big_tx/100_events-12            244.7Ki ±  0%    244.6Ki ±  0%  -0.05% (p=0.045 n=6)
geomean                                              31.43Ki          31.35Ki        -0.28%
¹ all samples are equal

                                            │ build/main/bench.out │              bench.out              │
                                            │      allocs/op       │  allocs/op   vs base                │
geomean                                                 144.7         144.7       +0.00%
¹ all samples are equal

```

_report generated with https://pkg.go.dev/golang.org/x/perf/cmd/benchstat_
<!--COMMENT_GENERATED_WITH_ID_bench.diff-->

2023-04-26 00:15 UTC, axw reviewed
@felixbarny do you think this is worth benchmarking, or would the design win anyway?

I wonder if we should drop that `remove` processor altogether. This has been around since forever, when we used to store a transaction document even for non-sampled transactions, and when we didn't have a default ILM delete phase . I feel like we have better options for storage management these days.

2023-04-26 06:33 UTC, felixbarny commented
If we already had synthetic _source, it would probably be a no-brainer to drop the `remove` processor altogether. Instinctively, I don't expect this to have a huge impact even now but I'd prefer to do some testing for that. If that testing would be very difficult to do (which I hope it isn't, that would kinda be another issue in itself) I suppose we could skip it if we preserve just `host` and `service.name`.

2023-04-28 01:21 UTC, axw approved these changes

2023-04-28 10:33 UTC, kruskall requested changes

2023-04-28 10:33 UTC, kruskall commented on changelogs/head.asciidoc
> +- Span events now carry `host` and `service.version` attributes.
```suggestion
- Span events now carry `host` and `service.version` attributes. {pull}10697[10697]
```

2023-04-28 16:01 UTC, merged

2023-06-29 03:48 UTC, axw commented
Verified with BC2. Send testdata/intake-v2/spans.ndjson to the hosted APM Server, confirmed that `host.*` and `service.version` fields are present in span documents.