docs: redirects for removed pages
elastic/apm-server pull request #10894
Opened 2023-05-25 12:13 UTC by abdonpijpelink

Reopening https://github.com/elastic/apm-server/pull/10891 to target `8.8`

2023-05-25 13:05 UTC, simitt approved these changes

2023-05-25 13:07 UTC, simitt requested changes
following redirects seem to be missing

```

INFO:build_docs:   - en/apm/guide/8.8/sourcemaps.html#sourcemap-rum-generate

INFO:build_docs:   - en/apm/guide/8.8/sourcemaps.html#sourcemap-rum-upload

INFO:build_docs:   - en/apm/guide/8.8/events-api.html#events-api-errors

INFO:build_docs:   - en/apm/guide/8.8/metadata-api.html#metadata-schema
```

2023-05-25 13:34 UTC, colleenmcginnis commented on docs/legacy/redirects.asciidoc
> +Please see <<apm-overview>>.
```suggestion
Please see <<apm-overview>>.

[role="exclude",id="sourcemap-rum-generate"]
=== Generate a source map

This page has been deleted.
Please see <<apm-overview>>.

[role="exclude",id="sourcemap-rum-upload"]
=== Upload the source map to Kibana

This page has been deleted.
Please see <<apm-overview>>.
```

2023-05-25 13:34 UTC, colleenmcginnis commented on docs/legacy/redirects.asciidoc
> +
```suggestion

[role="exclude",id="events-api-errors"]
=== Errors

This page has been deleted.
Please see <<apm-overview>>.

```

2023-05-25 13:34 UTC, colleenmcginnis commented on docs/legacy/redirects.asciidoc
> +
```suggestion

[role="exclude",id="metadata-schema"]
=== Metadata Schema

This page has been deleted.
Please see <<apm-overview>>.

```

2023-05-25 14:02 UTC, abdonpijpelink commented
@simitt It's passing all the checks now

2023-05-25 14:05 UTC, simitt approved these changes

2023-05-25 14:22 UTC, bmorelli25 approved these changes
Thanks everyone

2023-05-25 14:33 UTC, merged

2023-07-24 18:22 UTC, bmorelli25 commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.9|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/apm-server/11278">](https://github.com/elastic/apm-server/pull/11278)|
|✅|main|[<img src="https://img.shields.io/github/pulls/detail/state/elastic/apm-server/11279">](https://github.com/elastic/apm-server/pull/11279)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.9.7 -->