changelog: 8.15.3 release
elastic/apm-server pull request #14377
Opened 2024-10-16 15:23 UTC by inge4pres

2024-10-16 15:24 UTC, lahsivjar submitted a review, later dismissed

2024-10-16 15:38 UTC, inge4pres commented on changelogs/8.15.asciidoc
> +No significant changes.
thanks Carson, I was looking at https://github.com/elastic/apm-server/compare/v8.15.2...update-8.15.3

Is it this? https://github.com/elastic/apm-server/pull/13950

2024-10-16 15:50 UTC, inge4pres commented on changelogs/8.15.asciidoc
> +No significant changes.
I can only see these changes in the version diffs, 1.10.0 to 1.11.0
https://github.com/elastic/apm-data/compare/v1.10.0...v1.11.0

Apparently only https://github.com/elastic/apm-server/issues/13703 should be added?

2024-10-16 17:13 UTC, carsonip commented on changelogs/8.15.asciidoc
> +No significant changes.
Should be https://github.com/elastic/apm-data/compare/v1.9.1...v1.11.0 if I'm looking at v8.15.2 correctly.
On top of #13703, there's https://github.com/elastic/apm-data/pull/339 . @lahsivjar any otel lib changes that are significant?

2024-10-16 19:30 UTC, 1pkg reviewed
We also merged https://github.com/elastic/apm-server/pull/13884 in 8.15.3, originally I didn't add any changelog record for this, but now I'm not sure if we should?

2024-10-17 02:47 UTC, marclop approved these changes

2024-10-17 08:56 UTC, inge4pres commented on changelogs/8.15.asciidoc
> +No significant changes.
Yep, you are correct https://github.com/elastic/apm-server/blob/v8.15.2/go.mod#L10
Though I don't see apm-data PR 339 in https://github.com/elastic/apm-data/compare/v1.9.1...v1.11.0

2024-10-17 09:01 UTC, inge4pres commented
> I'm not sure if we should?

Personally i vote for not including it, because it's not a user-visible change that impacts consuming the product.

2024-10-18 03:10 UTC, carsonip commented on changelogs/8.15.asciidoc
> +No significant changes.
> Though I don't see apm-data PR 339 in https://github.com/elastic/apm-data/compare/v1.9.1...v1.11.0

Commit message was too long. It is the one from [Martijn Laarman](https://github.com/Mpdreamz)

2024-10-18 03:18 UTC, carsonip requested changes
sorry for being a PITA every time about changelogs. I realize I was wrong in https://github.com/elastic/apm-server/pull/14186 . The apm-data backport didn't make it on time, and there were 2 entries in 8.15.2 actually slipped into 8.15.3.

2024-10-18 03:18 UTC, carsonip commented on changelogs/8.15.asciidoc
> +- Fix a panic in OTLP intake protocol, occurring when invalid format of data was included in arrays {pull}13703[13703]
```suggestion
- Fix a panic in OTLP label setting when receiving on non-compliant attribute array values {pull}13950[13950]

[float]
==== Added

- Map OpenTelemetry instrumentation scope to `Service.Framework.*` for all signal types. {pull}13903[13903]
```

2024-10-18 03:18 UTC, carsonip commented on changelogs/8.15.asciidoc
>  === APM version 8.15.2
Can you delete the relevant lines (30 and 35) in 8.15.2, they are moved to 8.15.3. I hate the github review UI.

2024-10-18 07:57 UTC, inge4pres commented on changelogs/8.15.asciidoc
> +No significant changes.
Apologies... I'll add

2024-10-18 08:29 UTC, inge4pres commented on changelogs/8.15.asciidoc
> +No significant changes.
mhmhm that change is already in 8.15.2 changelog entry, not sure why.
https://github.com/elastic/apm-server/blob/d218c50f62ce4e34f449c334517268aeed6f56fc/changelogs/8.15.asciidoc#L32-L35

2024-10-18 08:38 UTC, inge4pres commented
> sorry for being a PITA every time about changelogs.

nw, actually thanks so much for your help on this 🙏🏼 
looking forward to automating away all these steps

2024-10-18 08:48 UTC, carsonip approved these changes

2024-10-18 10:01 UTC, merged