feat: bump badger to v4
elastic/apm-server pull request #14427
Opened 2024-10-23 12:05 UTC by kruskall

## Motivation/summary

badger v2 is ancient

use a separate folder for badgerv4 DB and drop old data

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

## Related issues

Closes https://github.com/elastic/apm-server/issues/11546

2024-10-24 04:00 UTC, marclop reviewed
Can you add some tests for the new behavior?

2024-10-24 04:00 UTC, marclop commented on x-pack/apm-server/sampling/processor_test.go
> +	t.Skip("SKIP")
Is there a compelling reason to sneak this into this commit?

2024-10-24 04:00 UTC, marclop commented on x-pack/apm-server/main.go
> +	if entries, err := os.ReadDir(oldTailSamplingStorageDir); err == nil {
I don't see any tests ensuring this works, could you add some, please?

2024-10-24 19:43 UTC, 1pkg commented on x-pack/apm-server/main.go
> +	if entries, err := os.ReadDir(oldStorageDir); err == nil {
Do we want to log the error if the syscall to open a directory has failed here? i.e. specifically checking for `err != nil && err != io.EOF`

2024-10-24 19:43 UTC, 1pkg approved these changes

2024-10-25 04:11 UTC, marclop requested changes
Can you add a changelog entry? This seems like the kind of change that needs a changelog entry.

2024-11-04 08:45 UTC, simitt commented
@kruskall I think this should be closed based on the findings and the workaround you applied.

2024-11-04 13:19 UTC, closed without merging