Add service name to logs
elastic/apm-server pull request #5355
Opened 2021-05-27 11:50 UTC by jalvz

Implements part of https://github.com/elastic/apm-server/issues/5034

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)

## How to test these changes

Send some events to apm-server, check that `service.name` is in the request logs

2021-05-27 11:59 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5355/detail/PR-5355/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5355/detail/PR-5355/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5355/detail/PR-5355/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5355/detail/PR-5355/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_5355.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #5355 opened`



* Start Time: 2021-05-27T11:51:02.994+0000


* Duration: 8 min 10 sec


* Commit: eb1b71a5bcd12e23c0db1e314ae8f5316a735ec4




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5355/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5355/detail/PR-5355/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Run intake`
<ul>
<li>Took 4 min 17 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-5355/runs/1/steps/125/log/?start=0">here</a></li>
<li>Description: <code>./.ci/scripts/intake.sh</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-05-27T11:57:27.978Z] Running dependency: Config
[2021-05-27T11:57:27.978Z] Running dependency: Fields
[2021-05-27T11:57:27.978Z] >> Building apm-server.yml for linux/amd64
[2021-05-27T11:57:27.978Z] exec: go list -m -f {{.Dir}} github.com/elastic/beats/v7
[2021-05-27T11:57:27.978Z] >> Building apm-server.docker.yml for linux/amd64
[2021-05-27T11:57:28.241Z] Found Elastic Beats dir at /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c
[2021-05-27T11:57:28.241Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c/libbeat/scripts/cmd/global_fields/main.go -es_beats_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c -beat_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server -out build/fields/fields.yml model
[2021-05-27T11:57:28.821Z] Generated fields.yml for apm-server to /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server/build/fields/fields.yml
[2021-05-27T11:57:28.821Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c/dev-tools/cmd/asset/asset.go -pkg include -in build/fields/fields.yml -out include/fields.go -license ASL2 apm-server
[2021-05-27T11:57:29.393Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c/libbeat/scripts/cmd/global_fields/main.go -es_beats_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c -beat_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server -out build/fields/fields.all.yml model /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server/x-pack/apm-server
[2021-05-27T11:57:29.973Z] Generated fields.yml for apm-server to /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server/build/fields/fields.all.yml
[2021-05-27T11:57:29.973Z] >> Generating docs/fields.asciidoc for apm-server
[2021-05-27T11:57:29.973Z] exec: /tmp/tmp.CVBOpZgdaM/python-env/build/ve/linux/bin/python3 /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c/libbeat/scripts/generate_fields_docs.py build/fields/fields.all.yml apm-server /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210512112333-7d75d02b1f0c --output_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server
[2021-05-27T11:57:32.571Z] /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/.gvm/versions/go1.15.12.linux.amd64/bin/go build -o build/linux/goimports golang.org/x/tools/cmd/goimports
[2021-05-27T11:57:37.877Z] Checking apmpackage/apm/0.2.0
[2021-05-27T11:57:37.877Z] Format the package
[2021-05-27T11:57:37.878Z] Done
[2021-05-27T11:57:37.878Z] Lint the package
[2021-05-27T11:57:37.878Z] Done
[2021-05-27T11:57:37.878Z] Build the package
[2021-05-27T11:57:37.878Z] Package built: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5355/src/github.com/elastic/apm-server/build/integrations/apm/0.2.0
[2021-05-27T11:57:37.878Z] Done
[2021-05-27T11:57:37.878Z] 2021/05/27 11:57:37 exec: go list -m
[2021-05-27T11:57:38.138Z] Running target: Check
[2021-05-27T11:57:38.138Z] >> check: Checking source code for common problems
[2021-05-27T11:57:38.138Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.CheckYAMLNotExecutable
[2021-05-27T11:57:38.138Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.GoVet
[2021-05-27T11:57:38.138Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.CheckPythonTestNotExecutable
[2021-05-27T11:57:38.138Z] exec: go vet ./...
[2021-05-27T11:57:38.398Z] go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
[2021-05-27T11:57:38.398Z] go: downloading github.com/elastic/go-hdrhistogram v0.1.0
[2021-05-27T11:57:38.398Z] go: downloading github.com/stretchr/testify v1.7.0
[2021-05-27T11:57:38.398Z] go: downloading github.com/dgraph-io/badger v1.6.2
[2021-05-27T11:57:38.398Z] go: downloading github.com/aws/aws-sdk-go-v2 v0.18.0
[2021-05-27T11:57:38.398Z] go: downloading github.com/hashicorp/nomad/api v0.0.0-20201203164818-6318a8ac7bf8
[2021-05-27T11:57:38.398Z] go: downloading github.com/cloudfoundry/noaa v2.1.0+incompatible
[2021-05-27T11:57:38.398Z] go: downloading github.com/cloudfoundry-community/go-cfclient v0.0.0-20190808214049-35bcce23fc5f
[2021-05-27T11:57:38.398Z] go: downloading github.com/ianlancetaylor/demangle v0.0.0-20200824232613-28f6c0f3b639
[2021-05-27T11:57:38.661Z] go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
[2021-05-27T11:57:38.661Z] go: downloading github.com/dgraph-io/badger/v2 v2.2007.3-0.20201012072640-f5a7e0a1c83b
[2021-05-27T11:57:38.661Z] go: downloading code.cloudfoundry.org/go-loggregator v7.4.0+incompatible
[2021-05-27T11:57:38.661Z] go: downloading github.com/pmezard/go-difflib v1.0.0
[2021-05-27T11:57:38.661Z] go: downloading github.com/gorilla/websocket v1.4.2
[2021-05-27T11:57:38.661Z] go: downloading github.com/hashicorp/cronexpr v1.1.0
[2021-05-27T11:57:38.661Z] go: downloading code.cloudfoundry.org/gofileutils v0.0.0-20170111115228-4d0c80011a0f
[202 [...]

2021-05-28 03:24 UTC, axw requested changes
Explicitly adding `service.name` to every log message is going to be difficult and error-prone to maintain. Moreover, we should be adding the fields to log messages coming from libbeat too.

The service name is the beat name, and that's [already known to logp](https://github.com/elastic/beats/blob/e5b976a3bee54553b96b82be8bbaf1e6835c280d/libbeat/logp/config.go#L29), so can we add the field centrally in logp? It should be possible to do this with a `zap.Fields` option, or with `zap.Logger.WithFields`.

Given that we'll also need to set `event.dataset` as part of https://github.com/elastic/apm-server/issues/5034, maybe we should add an option in ecszap for setting both `service.name` and `event.dataset`?

2021-05-28 07:32 UTC, jalvz commented
> The service name is the beat name

I understood it was the apm service name, not the beat name. The this doesn't make sense, closing.

2021-05-28 07:32 UTC, closed without merging

2021-07-06 07:58 UTC, axw commented
Tested changed made in https://github.com/elastic/beats/pull/25998, using 7.14 BC1. Example apm-server log record:

```
localtesting_7.14.0_apm-server | {"log.level":"info","@timestamp":"2021-07-06T07:56:51.344Z","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":63},"message":"request ok","service.name":"apm-server","event.dataset":"apm-server","url.original":"/","http.request.method":"GET","user_agent.original":"curl/7.29.0","source.address":"127.0.0.1","http.request.body.bytes":0,"http.request.id":"bb9ec214-10f0-4c7a-95d9-1c48bcf50928","event.duration":97785,"http.response.status_code":200,"ecs.version":"1.6.0"}
```

Notably, `service.name` and `event.dataset` fields are there.