Introduce `apm-server.auth.*` config
elastic/apm-server pull request #5457
Opened 2021-06-15 10:04 UTC by axw

## Motivation/summary

Introduce the new AgentAuth config structure, which holds API Key and secret token auth. Later we will add "anonymous" auth here too, and deprecate/replace some RUM config (rate limiting and allowed service names).

We also introduce a new YAML naming scheme for the config, `apm-server.auth.*`. The old config is deprecated and copied across to the new config fields.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

## How to test these changes

1. Set `apm-server.secret_token` and `apm-server.api_key.*`, make sure they are honoured (e.g. query "GET /" with/out auth)
2. Set `apm-server.auth.secret_token` and `apm-server.auth.api_key.*`, same again.
3. Set both new and old with different values: check that a warning is logged that the old config is ignored, and check that it is possible to auth using the new but not old

## Related issues

https://github.com/elastic/apm-server/issues/5347

2021-06-15 10:08 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5457/detail/PR-5457/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5457/detail/PR-5457/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5457/detail/PR-5457/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5457/detail/PR-5457/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_5457.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #5457 opened`



* Start Time: 2021-06-15T10:04:40.220+0000


* Duration: 4 min 43 sec


* Commit: 8647dda1f75da317beba525ac06f3017aadbdf43




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5457/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5457/detail/PR-5457/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-5457/runs/1/steps/11/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-15T10:07:10.757Z] The recommended git tool is: git
[2021-06-15T10:07:12.958Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 5 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-5457/runs/1/steps/15/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-15T10:07:39.012Z] The recommended git tool is: git
[2021-06-15T10:07:39.021Z] using creden</code></l1>
</ul>
  
  
  
  
##### `Check out from version control`
<ul>
<li>Took 0 min 7 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-5457/runs/1/steps/19/log/?start=0">here</a></li>
<li>Description: <code>[2021-06-15T10:08:14.612Z] The recommended git tool is: git
[2021-06-15T10:08:14.634Z] using creden</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-15T10:07:39.083Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2021-06-15T10:07:39.088Z]  > git fetch --no-tags --progress -- git@github.com:elastic/apm-server.git +refs/heads/*:refs/remotes/origin/* # timeout=15
[2021-06-15T10:07:43.720Z] Cleaning workspace
[2021-06-15T10:07:43.733Z] Using shallow fetch with depth 3
[2021-06-15T10:07:43.733Z] Pruning obsolete local branches
[2021-06-15T10:07:44.438Z] Merging remotes/origin/master commit f7c7b0c6873d40f533c072b3d9751c8fe285e63e into PR head commit 8647dda1f75da317beba525ac06f3017aadbdf43
[2021-06-15T10:07:44.468Z] ERROR: Execution failed
[2021-06-15T10:07:44.468Z] hudson.plugins.git.GitException: Command "git checkout -f 8647dda1f75da317beba525ac06f3017aadbdf43" returned status code 128:
[2021-06-15T10:07:44.468Z] stdout: 
[2021-06-15T10:07:44.468Z] stderr: fatal: reference is not a tree: 8647dda1f75da317beba525ac06f3017aadbdf43
[2021-06-15T10:07:44.468Z] 
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2639)
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:84)
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2956)
[2021-06-15T10:07:44.468Z] Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from apm-ci-immutable-ubuntu-1804-1623751497245822780.c.elastic-ci-prod.internal/10.224.1.15:55916
[2021-06-15T10:07:44.468Z] 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
[2021-06-15T10:07:44.468Z] 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
[2021-06-15T10:07:44.468Z] 		at hudson.remoting.Channel.call(Channel.java:1001)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
[2021-06-15T10:07:44.468Z] 		at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source)
[2021-06-15T10:07:44.468Z] 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-06-15T10:07:44.468Z] 		at java.lang.reflect.Method.invoke(Method.java:498)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
[2021-06-15T10:07:44.468Z] 		at com.sun.proxy.$Proxy136.execute(Unknown Source)
[2021-06-15T10:07:44.468Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.checkout(MergeWithGitSCMExtension.java:145)
[2021-06-15T10:07:44.468Z] 		at jenkins.plugins.git.MergeWithGitSCMExtension.decorateRevisionToBuild(MergeWithGitSCMExtension.java:111)
[2021-06-15T10:07:44.468Z] 		at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1163)
[2021-06-15T10:07:44.468Z] 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
[2021-06-15T10:07:44.468Z] 		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[2021-06-15T10:07:44.468Z] 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2021-06-15T10:07:44.468Z] 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2021-06-15T10:07:44.468Z] 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2021-06-15T10:07:44.468Z] 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2021-06-15T10:07:44.468Z] Caused: hudson.plugins.git.GitException: Could not checkout 8647dda1f75da317beba525ac06f3017aadbdf43
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2980)
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
[2021-06-15T10:07:44.468Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
[2021-06-15T10:07:44.468Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
[2021-06-15T10:07:44.468Z] 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
[2021-06-15T10:07:44.468Z] 	at hudson.remoting.Request$2.run(Request.java:375)
[2021-06-15T10:07:44.468Z] 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
[2021-06-15T10:07:44.468Z] 	at java.util.concurrent.FutureTask.run(FutureTask. [...]

2021-06-15 14:54 UTC, simitt reviewed
Looks great.

2021-06-15 14:54 UTC, simitt commented on docs/configuration-process.asciidoc
> +deprecated::[7.14.0, "In versions prior to 7.14.0, secret token authorization was known as `apm-server.secret_token`. In 7.14.0 this was renamed `apm-server.auth.secret_Token`. The old configuration
typo: `secret_Token`

2021-06-16 03:28 UTC, axw commented on docs/configuration-process.asciidoc
> +deprecated::[7.14.0, "In versions prior to 7.14.0, secret token authorization was known as `apm-server.secret_token`. In 7.14.0 this was renamed `apm-server.auth.secret_Token`. The old configuration
thanks, fixed

2021-06-16 03:53 UTC, axw commented
@bmorelli25 would you please take a look at the docs changes? I've renamed some config, and added new deprecation sections for the deprecated config names.

I've also moved "api_key.* configuration options" into the "API keys" section, not sure if it was intentional that it was separate? I can move back if you prefer, but then I'm not sure where the deprecation section should go.

2021-06-16 06:08 UTC, simitt requested changes
Can you also change the `apmpackage` please. I suggest we remove the deprecated settings and only support the new ones.

2021-06-16 07:17 UTC, axw commented
@simitt will do. I was going to wait for your changes (https://github.com/elastic/apm-server/pull/5444) to land, but I'll just update now for the purposes of review and update again when that lands.

2021-06-16 10:44 UTC, simitt approved these changes

2021-06-16 18:35 UTC, bmorelli25 approved these changes
Docs look great–thanks!

It looks like there's one [additional change](https://github.com/elastic/apm-server/blame/master/docs/copied-from-beats/docs/command-reference.asciidoc/#L142-L143) that needs to be made to the command reference file. I'll fix that in the Beats repo and copy it over to apm-server before 7.14.

2021-06-17 03:17 UTC, axw commented
Failure is related to the beats update, which will be resolved by https://github.com/elastic/apm-server/pull/5471

2021-06-17 03:17 UTC, merged

2021-07-09 14:20 UTC, simitt commented
Tested with BC2:
* old settings work as expected
* new settings work as expected
* API Key auth disabled when:
```
apm-server.api_key.enabled: true
apm-server.auth.api_key.enabled: false
```
  * Secret token 'abcd' expected
```
apm-server.secret_token: 'xxx'
apm-server.auth.secret_token: 'abcd'
```