deprecate span destination name and type fields
elastic/apm-server pull request #5468
Opened 2021-06-16 12:52 UTC by jalvz

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

## How to test these changes

Send some events to apm-server with span.destination.service.resource and without span.destination.service.name nor span.destination.service.type.
Events should be accepted.

## Related issues

Closes  https://github.com/elastic/apm-server/issues/5466

2021-06-16 14:50 UTC, simitt requested changes
To make the change on the Intake API you need to add a `Deprecated` note in the comment and remove the `required` tag in the [modeldecoder](https://github.com/elastic/apm-server/blob/master/model/modeldecoder/v2/model.go#L702-L707). Running `make update` will update the `docs/spec` accordingly. (Same for rumv3 modeldecoder).

2021-06-16 18:51 UTC, jalvz commented
thanks @simitt , didn't know about that

2021-06-16 18:54 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5468/detail/PR-5468/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5468/detail/PR-5468/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5468/detail/PR-5468/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5468/detail/PR-5468/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #5468 updated`


* Reason: `Aborted from #2`


* Start Time: 2021-06-16T18:48:50.711+0000


* Duration: 5 min 4 sec


* Commit: 1e8633ff172c285c52a105b3062072d6c0b76204




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5468/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-16T18:53:45.289Z] Collecting paramiko>=2.4.2
[2021-06-16T18:53:45.289Z]   Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
[2021-06-16T18:53:45.547Z] Collecting bcrypt>=3.1.3
[2021-06-16T18:53:45.547Z]   Downloading bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
[2021-06-16T18:53:45.805Z] Collecting cryptography>=2.5
[2021-06-16T18:53:45.805Z]   Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
[2021-06-16T18:53:46.063Z] Collecting pynacl>=1.0.1
[2021-06-16T18:53:46.063Z]   Downloading PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
[2021-06-16T18:53:46.628Z] Collecting cffi>=1.1
[2021-06-16T18:53:46.628Z]   Downloading cffi-1.14.5-cp36-cp36m-manylinux1_x86_64.whl (401 kB)
[2021-06-16T18:53:46.628Z] Collecting pycparser
[2021-06-16T18:53:46.628Z]   Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
[2021-06-16T18:53:46.628Z] Building wheels for collected packages: autopep8, backports.ssl-match-hostname, dockerpty, docopt, ipaddress, jsondiff, ordered-set, pyrsistent, PyYAML, stomp.py, termcolor, texttable
[2021-06-16T18:53:46.628Z]   Building wheel for autopep8 (setup.py): started
[2021-06-16T18:53:46.887Z]   Building wheel for autopep8 (setup.py): finished with status 'done'
[2021-06-16T18:53:46.887Z]   Created wheel for autopep8: filename=autopep8-1.5.4-py2.py3-none-any.whl size=45287 sha256=f242fdcd071911150e2c562c44ddb84643a343bacedbd2f9b93260ee4ed7cb85
[2021-06-16T18:53:46.887Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/60/2d/2e/bb7391b33bdeaa7037d4e52e7cdacc3712932c67f202d9e886
[2021-06-16T18:53:46.887Z]   Building wheel for backports.ssl-match-hostname (setup.py): started
[2021-06-16T18:53:47.145Z]   Building wheel for backports.ssl-match-hostname (setup.py): finished with status 'done'
[2021-06-16T18:53:47.145Z]   Created wheel for backports.ssl-match-hostname: filename=backports.ssl_match_hostname-3.5.0.1-py3-none-any.whl size=5206 sha256=6d623a27410c78ef90c39b51ee5ba9a4187498a57e121121b361dab5790292f3
[2021-06-16T18:53:47.145Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/05/b9/92/62f119d7e440645ddda5da202b010919bef868a3e2d1dae8f4
[2021-06-16T18:53:47.145Z]   Building wheel for dockerpty (setup.py): started
[2021-06-16T18:53:47.403Z]   Building wheel for dockerpty (setup.py): finished with status 'done'
[2021-06-16T18:53:47.403Z]   Created wheel for dockerpty: filename=dockerpty-0.4.1-py3-none-any.whl size=16605 sha256=372bfc18e34d8c210b5d3b3e07452cad5b814888651eaae6db9a53afd0008ba7
[2021-06-16T18:53:47.403Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/61/8f/e3/247046231ee138b48be905e4a748d570630e1f3ec24632b00b
[2021-06-16T18:53:47.403Z]   Building wheel for docopt (setup.py): started
[2021-06-16T18:53:47.660Z]   Building wheel for docopt (setup.py): finished with status 'done'
[2021-06-16T18:53:47.660Z]   Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13705 sha256=9e15950751ab9e358114e19e7ee2da212e7a647446673c743cc7e61a1f887052
[2021-06-16T18:53:47.660Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/3f/2a/fa/4d7a888e69774d5e6e855d190a8a51b357d77cc05eb1c097c9
[2021-06-16T18:53:47.660Z]   Building wheel for ipaddress (setup.py): started
[2021-06-16T18:53:47.918Z]   Building wheel for ipaddress (setup.py): finished with status 'done'
[2021-06-16T18:53:47.919Z]   Created wheel for ipaddress: filename=ipaddress-1.0.19-py3-none-any.whl size=18138 sha256=fe030db799837e0c685fe55ed5ed8997425249ac8ceb2d23c6b0a0ffdca3b83c
[2021-06-16T18:53:47.919Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/d6/8a/fc/306ac211c6ee12704e49e521a7e7a201be90595d0faf6e7e21
[2021-06-16T18:53:47.919Z]   Building wheel for jsondiff (setup.py): started
[2021-06-16T18:53:48.176Z]   Building wheel for jsondiff (setup.py): finished with status 'done'
[2021-06-16T18:53:48.176Z]   Created wheel for jsondiff: filename=jsondiff-1.1.2-py3-none-any.whl size=6466 sha256=ef0db9c496e79fc2f276617d473e10d4311636ec8208628ed3e25ef67b4e134f
[2021-06-16T18:53:48.176Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/e3/8b/97/8a62d503d5391bf0a61b47e910deb5d745e8d9d76699ddf986
[2021-06-16T18:53:48.176Z]   Building wheel for ordered-set (setup.py): started
[2021-06-16T18:53:48.434Z]   Building wheel for ordered-set (setup.py): finished with status 'done'
[2021-06-16T18:53:48.434Z]   Created wheel for ordered-set: filename=ordered_set-3.1.1-py2.py3-none-any.whl size=7812 sha256=0da63a3d412a2b463837b54c29dcc64293bad8ec3b6549e98de0fb7ab18b0889
[2021-06-16T18:53:48.434Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/17/b5/3e/8ce33554f56742a00afbe043d72753c2d8997e761e72114b04
[2021-06-16T18:53:48.434Z]   Building wheel for pyrsistent (setup.py): started
[2021-06-16T18:53:49.437Z]   Building wheel for pyrsistent (setup.py): finished with status 'done'
[2021-06-16T18:53:49.437Z]   Created wheel for pyrsistent: filename=pyrsistent-0.16.0-cp36-cp36m-linux_x86_64.whl size=97773 sha256=802a05f6ea693579e6cd82fa4c176cff815f6de472b10f502860204faf25f8eb
[2021-06-16T18:53:49.437Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/d1/8a/1c/32ab9017418a2c64e4fbaf503c08648bed2f8eb311b869a464
[2021-06-16T18:53:49.437Z]   Building wheel for PyYAML (setup.py): started
[2021-06-16T18:53:49.696Z]   Building wheel for PyYAML (setup.py): finished with status 'done'
[2021-06-16T18:53:49.696Z]   Created wheel for PyYAML: filename=PyYAML-5.3.1-cp36-cp36m-linux_x86_64.whl size=44621 sha256=8430ed518576e0f22bf6cf392136b9174ac5aa85c516d435137f7f39a10152b4
[2021-06-16T18:53:49.696Z]   Stored in directory: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5468/.cache/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
[2021-06-16T18:53:49.696Z]   Building wheel for stomp.py (setup.py): started
[2021-06-16T18:53:49.815Z] Sending interrupt signal to process
[2021-06-16T18:53:49.955Z]   Building wheel for stomp.py (setup.py): finished with status 'error'
[2021-06-16T18:53:49. [...]

2021-06-16 18:54 UTC, simitt commented on model/modeldecoder/v2/model.go
> +	// This field is DEPRECATED and will be removed in a future release
nit: Could you start with the deprecated note so it shows up at the beginning of the Intake API comment?
Similar to https://github.com/elastic/apm-server/blob/f29f10905bde682d833866c0881f282b88c881b3/model/modeldecoder/v2/model.go#L495

2021-06-17 14:12 UTC, simitt approved these changes

2021-06-17 19:38 UTC, merged

2021-07-06 07:45 UTC, axw commented
Tested with 7.14 BC1. I hacked the Go Agent to not send the destination service type or name, only resource; the server accepted this and record resource and neither of the other empty/missing fields.