record per-agent config status
elastic/apm-server pull request #5481
Opened 2021-06-17 09:47 UTC by stuartnelson3

## Motivation/summary

Record the clientIP, service name, service
environment, and etag for the applied config, for
each agent request. This can be used to see the
current state of config application, convergence
towards a new config, or if there are services
that are running old config versions.

closes https://github.com/elastic/apm-server/issues/5470

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/master/CHANGELOG.asciidoc)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

Running apm-server under fleet, start an agent that requests its config from apm-server. Update the config, and verify that the timeseries has been ingested into elasticsearch.

2021-06-17 09:55 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5481/detail/PR-5481/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5481/detail/PR-5481/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5481/detail/PR-5481/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5481/detail/PR-5481/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_5481.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #5481 opened`



* Start Time: 2021-06-17T09:47:23.606+0000


* Duration: 8 min 57 sec


* Commit: f78f8a0b2dff242bbc23cd11899cd307f0382c52




#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-server/job/apm-server-mbp/job/PR-5481/buildTimeGraph/png)



</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-5481/detail/PR-5481/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Run intake`
<ul>
<li>Took 4 min 10 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-5481/runs/1/steps/125/log/?start=0">here</a></li>
<li>Description: <code>./.ci/scripts/intake.sh</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-06-17T09:52:57.056Z] Running target: Update
[2021-06-17T09:52:57.056Z] Running dependency: Config
[2021-06-17T09:52:57.056Z] >> Building apm-server.yml for linux/amd64
[2021-06-17T09:52:57.056Z] Running dependency: Fields
[2021-06-17T09:52:57.056Z] exec: go list -m -f {{.Dir}} github.com/elastic/beats/v7
[2021-06-17T09:52:57.056Z] >> Building apm-server.docker.yml for linux/amd64
[2021-06-17T09:52:57.056Z] Found Elastic Beats dir at /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a
[2021-06-17T09:52:57.056Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a/libbeat/scripts/cmd/global_fields/main.go -es_beats_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a -beat_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server -out build/fields/fields.yml model
[2021-06-17T09:52:57.056Z] Generated fields.yml for apm-server to /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server/build/fields/fields.yml
[2021-06-17T09:52:57.056Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a/dev-tools/cmd/asset/asset.go -pkg include -in build/fields/fields.yml -out include/fields.go -license ASL2 apm-server
[2021-06-17T09:52:57.056Z] exec: go run -mod=readonly /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a/libbeat/scripts/cmd/global_fields/main.go -es_beats_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a -beat_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server -out build/fields/fields.all.yml model /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server/x-pack/apm-server
[2021-06-17T09:52:57.621Z] Generated fields.yml for apm-server to /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server/build/fields/fields.all.yml
[2021-06-17T09:52:57.621Z] >> Generating docs/fields.asciidoc for apm-server
[2021-06-17T09:52:57.621Z] exec: /tmp/tmp.eVeCRz6nNO/python-env/build/ve/linux/bin/python3 /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a/libbeat/scripts/generate_fields_docs.py build/fields/fields.all.yml apm-server /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/pkg/mod/github.com/elastic/beats/v7@v7.0.0-alpha2.0.20210614232151-2871d29be93a --output_path /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server
[2021-06-17T09:53:00.151Z] /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/.gvm/versions/go1.16.5.linux.amd64/bin/go build -o build/linux/goimports golang.org/x/tools/cmd/goimports
[2021-06-17T09:53:03.441Z] Format the package
[2021-06-17T09:53:03.700Z] Done
[2021-06-17T09:53:03.700Z] Lint the package
[2021-06-17T09:53:03.700Z] Done
[2021-06-17T09:53:03.700Z] Build the package
[2021-06-17T09:53:03.700Z] Package built: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-5481/src/github.com/elastic/apm-server/build/integrations/apm/0.3.0
[2021-06-17T09:53:03.700Z] Done
[2021-06-17T09:53:03.700Z] 2021/06/17 09:53:03 exec: go list -m
[2021-06-17T09:53:03.700Z] Running target: Check
[2021-06-17T09:53:03.700Z] >> check: Checking source code for common problems
[2021-06-17T09:53:03.700Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.CheckYAMLNotExecutable
[2021-06-17T09:53:03.700Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.GoVet
[2021-06-17T09:53:03.700Z] Running dependency: github.com/elastic/beats/v7/dev-tools/mage.CheckPythonTestNotExecutable
[2021-06-17T09:53:03.700Z] exec: go vet ./...
[2021-06-17T09:53:03.959Z] go: downloading github.com/stretchr/testify v1.7.0
[2021-06-17T09:53:03.959Z] go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
[2021-06-17T09:53:03.959Z] go: downloading github.com/elastic/go-hdrhistogram v0.1.0
[2021-06-17T09:53:03.959Z] go: downloading github.com/dgraph-io/badger v1.6.2
[2021-06-17T09:53:04.217Z] go: downloading github.com/pmezard/go-difflib v1.0.0
[2021-06-17T09:53:04.217Z] go: downloading github.com/dgraph-io/badger/v2 v2.2007.3-0.20201012072640-f5a7e0a1c83b
[2021-06-17T09:53:04.217Z] go: downloading github.com/aws/aws-sdk-go-v2 v0.18.0
[2021-06-17T09:53:07.498Z] go: downloading github.com/ianlancetaylor/demangle v0.0.0-20200824232613-28f6c0f3b639
[2021-06-17T09:53:07.498Z] go: downloading github.com/dgraph-io/ristretto v0.0.3-0.20200630154024-f66de99634de
[2021-06-17T09:53:07.498Z] go: downloading github.com/dgryski/go-farm v0.0.0-20200201041132-a6ae2369ad13
[2021-06-17T09:53:07.498Z] go: downloading github.com/hashicorp/nomad/api v0.0.0-20201203164818-6318a8ac7bf8
[2021-06-17T09:53:07.498Z] go: downloading code.cloudfoundry.org/go-loggregator v7.4.0+incompatible
[2021-06-17T09:53:07.498Z] go: downloading github.com/cloudfoundry-community/go-cfclient v0.0.0-20190808214049-35bcce23fc5f
[2021-06-17T09:53:07.498Z] go: downloading github.com/cloudfoundry/noaa v2.1.0+incompatible
[2021-06-17T09:53:07.498Z] go: downloading github.com/cloudfoundry/sonde-go v0.0.0-20171206171820-b33733203bb4
[2021-06-17T09:53:07.498Z] go: downloadi [...]

2021-06-18 02:52 UTC, axw reviewed
That's a neat use of the prometheus integration :slightly_smiling_face:

A have a couple of concerns:
 - I think the tracer is disabled unless libbeat instrumentation is enabled, and it's disabled by default. Enabling by default is not an option yet.
 - IIANM, the Prometheus client doesn't automatically forget label values once they've been seen. The agent config API can be called by RUM without any authentication, so we would need to delete label values to avoid memory exhaustion attacks.

As nice as it is to be able to see which agents are on what config version, we don't have that ability today. I think we should pare it back a bit to just do what we today, and we can expand on it later. I believe that today we just need a single dimension, etag. To avoid memory exhaustion we should only maintain and report metrics for currently known etag values.

2021-06-18 07:02 UTC, stuartnelson3 commented
>IIANM, the Prometheus client doesn't automatically forget label values once they've been seen. The agent config API can be called by RUM without any authentication, so we would need to delete label values to avoid memory exhaustion attacks.

That's a super good point. Even if someone is just in a highly dynamic environment, the number of different (legitimate) clientIPs could become an issue.

2021-06-18 07:10 UTC, stuartnelson3 commented
>I think the tracer is disabled unless libbeat instrumentation is enabled, and it's disabled by default. Enabling by default is not an option yet.

Should we move to indexing via es client then?

2021-06-18 07:40 UTC, axw commented
> Should we move to indexing via es client then?

I think we should use the libbeat publisher for now at least. I don't know exactly how that will look, but for example you could have `agentcfg.DirectFetcher` keep track of which config has been applied (queried with the current Etag value, or MarkAsAppliedByAgent); and then have something periodically scraping that and creating `model.Metricsets` and sending them to the batchProcessor passed to beater.newServer

2021-06-18 10:33 UTC, stuartnelson3 commented
K, pushed up an idea of how it might look. When you have a chance let me know what you think. If it's looking reasonable, what should I be putting into each `model.Metricset`?

2021-06-21 02:04 UTC, axw reviewed
This approach looks good. We should only report config as "applied" if one of the following is true though:
 - `agentcfg.Query.Etag == agentcfg.Result.Etag` (i.e. we know the agent has previously received the config)
 - `agentcfg.Query.MarkAsAppliedByAgent == true` (for clients that don't/can't use the Etag approach)

https://github.com/elastic/apm-server/blob/f5664d8196599758da0dd1e1c88771d24e0f4870/agentcfg/model.go#L58-L69

> If it's looking reasonable, what should I be putting into each model.Metricset?

Here's what I'd suggest:

```yaml
 - Metricset.Name: "agent_config"
 - Metricset.Labels: {"etag": <etag>}
 - Metricset.Samples:
   - Name: "agent_config_applied"
     Value: 1
```

The constant metric value is not ideal, but good enough to start with.

2021-06-22 10:23 UTC, stuartnelson3 commented on agentcfg/reporter.go
> +				r.applied[result.Source.Etag] = struct{}{}
:+1: makes sense

2021-06-22 10:34 UTC, stuartnelson3 commented on agentcfg/reporter.go
> +	applied map[string]struct{}
makes sense to me

2021-06-22 14:38 UTC, stuartnelson3 commented
jenkins run the tests

2021-06-22 15:03 UTC, stuartnelson3 commented on agentcfg/reporter.go
> +			query.MarkAsAppliedByAgent != nil && *query.MarkAsAppliedByAgent) {
Sort of wonky formatting, wasn't sure if i should collapse it all into a single boolean like this or if two would make it easier to read.

2021-06-23 04:12 UTC, axw requested changes
Basically LGTM, just need to make sure we select on ctx.Done() and don't do a naked send on the channel - that could block the handler on shutdown.

When we come to https://github.com/elastic/apm-server/issues/5487, we should make sure to check that these metrics are reported in a system test.

2021-06-23 04:12 UTC, axw commented on beater/server.go
> +		fetchReporter: fetchReporter,
can we give this a more descriptive name? it fetches and reports what? agentcfgFetchReporter?

2021-06-23 04:12 UTC, axw commented on agentcfg/reporter.go
> +				Labels:  make(common.MapStr, 1),
```suggestion
				Labels:  common.MapStr{"etag": etag},
```

2021-06-23 04:12 UTC, axw commented on agentcfg/reporter.go
> +			m.Labels.Put("etag", etag)
```suggestion
```

2021-06-23 11:42 UTC, stuartnelson3 commented on agentcfg/reporter.go
> +	result, err := r.f.Fetch(ctx, query)
`:facepalm:`

2021-06-28 02:58 UTC, axw approved these changes

2021-06-28 02:58 UTC, axw commented on agentcfg/reporter.go
> +		(query.Etag == result.Source.Etag || query.MarkAsAppliedByAgent) {
```suggestion
	if query.Etag == result.Source.Etag || query.MarkAsAppliedByAgent {
```

(we know err == nil due to check above)

2021-06-28 12:37 UTC, stuartnelson3 commented
/test

2021-06-28 13:33 UTC, stuartnelson3 commented
/test

2021-06-28 15:30 UTC, stuartnelson3 commented
/test

2021-06-29 02:35 UTC, merged