[jjbb] list for release and active branches
elastic/apm-server pull request #6561
Opened 2021-11-09 14:40 UTC by v1v

## Motivation/summary

Tidy up the Jenkisn Multibranch pipelines with only the active branches and release branches. In other words, all the automation with `mergify`, `dependabot` or the `bump automation` should not be added as branches.

2021-11-09 14:42 UTC, v1v commented on .ci/jobs/apm-server-mbp.yml
> +        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*)'
Avoid 
![image](https://user-images.githubusercontent.com/2871786/140944668-9a7f616f-66a3-4161-9567-c4615eb59fb9.png)

2021-11-09 14:42 UTC, v1v commented on .ci/jobs/update-json-schema.yml
> +          head-filter-regex: '^(master|PR-.*)$'
PR automation should only be caring about changes coming from the master branch. Otherwise it will cause duplicated PRs with the json schema.

2021-11-09 14:43 UTC, mdelapenya approved these changes

2021-11-09 15:20 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6561/detail/PR-6561/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6561/detail/PR-6561/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6561/detail/PR-6561/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6561/detail/PR-6561/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_6561.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2021-11-09T14:31:05.504Z&rangeTo=2021-11-09T14:51:05.504Z&transactionName=apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=75ea84c226c99b20af7dfd4ffc54c54a&transactionId=7c3b94584ac92928)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-09T14:41:05.504+0000


* Duration: 40 min 36 sec


* Commit: 82e6064bce4b9dd8fbabbb032a9868c0132c07d0



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 4  |
| Passed       | 6179  |
| Skipped      | 19 |
| Total        | 6202   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![4](https://img.shields.io/badge/4%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6561/detail/PR-6561/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Build and Test / System and Environment Tests / TestAgentConfig – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestAgentConfig
2021/11/09 15:02:35 Building apm-server...
2021/11/09 15:02:36 Built /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-6561/src/github.com/elastic/apm-server/apm-server
2021/11/09 15:02:55 Building image elastic-agent-systemtest:8.1.0-2fdb91c4-SNAPSHOT...
2021/11/09 15:03:00 Built image elastic-agent-systemtest:8.1.0-2fdb91c4-SNAPSHOT
2021/11/09 15:03:01 Starting container id: 91a11657df79 image: quay.io/testcontainers/ryuk:0.2.3
2021/11/09 15:03:02 Waiting for container id 91a11657df79 image: quay.io/testcontainers/ryuk:0.2.3
2021/11/09 15:03:02 Container is ready id: 91a11657df79 image: quay.io/testcontainers/ryuk:0.2.3
2021/11/09 15:03:02 Starting container id: 39f8490af5b1 image: elastic-agent-systemtest:8.1.0-2fdb91c4-SNAPSHOT
2021/11/09 15:03:03 Waiting for container id 39f8490af5b1 image: elastic-agent-systemtest:8.1.0-2fdb91c4-SNAPSHOT
    fleet_test.go:129: 
        	Error Trace:	fleet_test.go:129
        	            				agentconfig_test.go:51
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestAgentConfig
    fleet_test.go:119: elastic-agent logs: �������"Policy selected for enrollment:  
        �������i2021-11-09T15:03:04.728Z	INFO	cmd/enroll_cmd.go:442	Starting enrollment to URL: https://172.18.0.5:8220/
        �������)Successfully enrolled the Elastic Agent.
        �������r2021-11-09T15:03:05.506Z	INFO	cmd/enroll_cmd.go:248	Elastic Agent might not be running; unable to trigger restart
        �������U2021-11-09T15:03:05.614Z	INFO	application/application.go:67	Detecting execution mode
        �������V2021-11-09T15:03:05.615Z	INFO	application/application.go:92	Agent is managed by Fleet
        ��������2021-11-09T15:03:05.615Z	INFO	capabilities/capabilities.go:59	capabilities file not found in /usr/share/elastic-agent/state/capabilities.yml
        ��������2021-11-09T15:03:06.206Z	INFO	[composable.providers.docker]	docker/docker.go:43	Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
        �������M2021-11-09T15:03:06.207Z	INFO	[api]	api/server.go:62	Starting stats endpoint
        �������P2021-11-09T15:03:06.207Z	INFO	application/managed_mode.go:290	Agent is starting
        ��������2021-11-09T15:03:06.207Z	INFO	[api]	api/server.go:64	Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)
        �������Y2021-11-09T15:03:07.935Z	INFO	stateresolver/stateresolver.go:48	New State ID is wSEF79mr
        �������q2021-11-09T15:03:07.935Z	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 2 step(s)
        �������|2021-11-09T15:03:08.116Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for apm-server.8.1.0-SNAPSHOT
        ��������2021-11-09T15:03:08.674Z	INFO	log/reporter.go:40	2021-11-09T15:03:08Z - message: Application: apm-server--8.1.0-SNAPSHOT[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:09.320Z	INFO	log/reporter.go:40	2021-11-09T15:03:09Z - message: Application: apm-server--8.1.0-SNAPSHOT[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to RESTARTING: exited with code: 2 - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:09.320Z	INFO	log/reporter.go:40	2021-11-09T15:03:09Z - message: Application: apm-server--8.1.0-SNAPSHOT[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:09.321Z	INFO	log/reporter.go:40	2021-11-09T15:03:09Z - message: Application: apm-server--8.1.0-SNAPSHOT[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:09.953Z	INFO	log/reporter.go:40	2021-11-09T15:03:09Z - message: Application: apm-server--8.1.0-SNAPSHOT[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:14.689Z	INFO	log/reporter.go:40	2021-11-09T15:03:14Z - message: Application: filebeat--8.1.0-SNAPSHOT--36643631373035623733363936343635[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
        ��������2021-11-09T15:03:15.987Z	INFO	log/reporter.go:40	2021-11-09T15:03:15Z - message: Application: filebeat--8.1.0-SNAPSHOT--36643631373035623733363936343635[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
        �������
2021-11-09T15:03:20.526Z	INFO	log/reporter.go:40	2021-11-09T15:03:20Z - message: Application: metricbeat--8.1.0-SNAPSHOT--36643631373035623733363936343635[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
        �������X2021-11-09T15:03:20.533Z	INFO	stateresolver/stateresolver.go:66	Updating internal state
        �������
        2021-11-09T15:03:21.770Z	INFO	log/reporter.go:40	2021-11-09T15:03:21Z - message: Application: metricbeat--8.1.0-SNAPSHOT--36643631373035623733363936343635[66784f9b-41d1-4697-9986-8747cf01d5c3]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
        �������a2021-11-09T15:04:11.111Z	WARN	status/reporter.go:236	Elastic Agent status changed to: 'd [...]

2021-11-09 16:29 UTC, cachedout requested changes
I think we need to include tags here. Let me know what you think.

2021-11-09 16:29 UTC, cachedout commented on .ci/jobs/apm-server-check-changelogs-mbp.yml
> +        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*)'
```suggestion
        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*|v[0-9].*)'
```

2021-11-09 16:29 UTC, cachedout commented on .ci/jobs/apm-server-check-changelogs-mbp.yml
> +        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*)'
Include tags?

2021-11-09 16:29 UTC, cachedout commented on .ci/jobs/apm-server-mbp.yml
> +        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*)'
```suggestion
        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*|v[0-9].*)'
```

Include tags?

2021-11-09 17:03 UTC, v1v commented on .ci/jobs/apm-server-check-changelogs-mbp.yml
> +        head-filter-regex: '(master|6\.*|7\.*|8\.*|PR-.*)'
no, see L14 -> `discover-tags: false`

2021-11-09 17:04 UTC, cachedout approved these changes

2021-11-10 01:31 UTC, axw approved these changes

2021-11-10 09:42 UTC, v1v commented
Failures are unrelated to this particular change, since it's only about the Jenkins jobs in the UI.

2021-11-10 09:50 UTC, merged