update beats: fix new file location
elastic/apm-server pull request #6700
Opened 2021-11-23 17:19 UTC by v1v

## Motivation/summary

https://github.com/elastic/apm-server/pull/6287 moved the files to the `legacy` folder, lets update the scripts

2021-11-23 18:02 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6700/detail/PR-6700/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6700/detail/PR-6700/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6700/detail/PR-6700/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6700/detail/PR-6700/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_6700.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2021-11-23T17:10:03.982Z&rangeTo=2021-11-23T17:30:03.982Z&transactionName=apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=unknown&latencyAggregationType=avg&traceId=5e715a9b0cd282f9defbb951be82fecc&transactionId=16a258bf2abad8a9)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-11-23T17:20:03.982+0000


* Duration: 43 min 43 sec


* Commit: 5b416381072a5c4610b32e1fa94d1f53564a7fd1



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 5582  |
| Skipped      | 19 |
| Total        | 5601   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->











### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-6700/detail/PR-6700/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Build packages`
<ul>
<li>Took 24 min 16 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-6700/runs/1/steps/548/log/?start=0">here</a></li>
<li>Description: <code>./.ci/scripts/package.sh</code></l1>
</ul>
  
  </p>
  </details>


## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/hey-apm` : Run the hey-apm benchmark.


- `/package` : Generate and publish the docker images.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-11-24 00:26 UTC, axw requested changes

2021-11-24 00:26 UTC, axw commented on .ci/scripts/update-beats.sh
> +	docs/legacy/fields.asciidoc include/fields.go x-pack/apm-server/include/fields.go
```suggestion
	.go-version docs/version.asciidoc
```

```suggestion
	.go-version docs/version.asciidoc \
```

- version.asciidoc is still in docs, not docs/legacy
- fields.asciidoc _is_ in docs/legacy, but we're no longer updating it or generating include/fields.go. The integration package is the way forward, and apm-server no longer installs index templates, etc.

2021-11-24 00:26 UTC, axw commented on Makefile
> +	sed -i'.bck' -E -e "s#(:go-version): [0-9]+\.[0-9]+\.[0-9]+#\1: $$(cat .go-version)#g" docs/legacy/version.asciidoc
```suggestion
	sed -i'.bck' -E -e "s#(:go-version): [0-9]+\.[0-9]+\.[0-9]+#\1: $$(cat .go-version)#g" docs/version.asciidoc
```

2021-11-24 00:26 UTC, axw commented on magefile.go
> +		DocBranch:   filepath.Join(repo.RootDir, "docs/legacy/version.asciidoc"),
```suggestion
		DocBranch:   filepath.Join(repo.RootDir, "docs/version.asciidoc"),
```

2021-11-24 09:11 UTC, v1v commented on .ci/scripts/update-beats.sh
>  	.go-version docs/version.asciidoc \
```suggestion
	.go-version docs/version.asciidoc
```

2021-11-24 12:46 UTC, axw approved these changes
thank you :)

2021-11-24 13:36 UTC, merged