[apmpackage] add double quotes around allow_origins {{this}}
elastic/apm-server pull request #7682
Opened 2022-03-28 14:32 UTC by stuartnelson3

## Motivation/summary

the wrong {{this}} was double quoted in #7598;
double quote the correct {{this}}

closes #7508

## How to test these changes

See reproduction steps [here](https://github.com/elastic/kibana/issues/121934#issuecomment-1055098129)

2022-03-28 14:33 UTC, marclop approved these changes
This this LGTM

2022-03-28 15:04 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-7682/detail/PR-7682/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-7682/detail/PR-7682/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-7682/detail/PR-7682/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-7682/detail/PR-7682/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_7682.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-03-28T14:22:58.311Z&rangeTo=2022-03-28T14:42:58.311Z&transactionName=apm-server/apm-server-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=de84e88c1953bbde58b4ed6ad68112bb&transactionId=e8f99f98670d1a54)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-03-28T14:32:58.311+0000


* Duration: 32 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 7  |
| Passed       | 3928  |
| Skipped      | 13 |
| Total        | 3948   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![7](https://img.shields.io/badge/7%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-7682/detail/PR-7682/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Build and Test / System and Environment Tests / TestAgentConfig – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestAgentConfig
2022/03/28 15:01:34 Building apm-server...
2022/03/28 15:01:35 Built /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-7682/src/github.com/elastic/apm-server/apm-server
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				agentconfig_test.go:51
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestAgentConfig
    server.go:191: log file: /var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-7682/src/github.com/elastic/apm-server/systemtest/logs/TestAgentConfig/apm-server
--- FAIL: TestAgentConfig (23.86s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestFleetIntegration – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestFleetIntegration
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				fleet_test.go:48
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestFleetIntegration
--- FAIL: TestFleetIntegration (4.01s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestFleetIntegrationBeatsMonitoring – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestFleetIntegrationBeatsMonitoring
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				fleet_test.go:64
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestFleetIntegrationBeatsMonitoring
--- FAIL: TestFleetIntegrationBeatsMonitoring (4.02s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestFleetIntegrationAnonymousAuth – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestFleetIntegrationAnonymousAuth
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				fleet_test.go:104
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 33, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestFleetIntegrationAnonymousAuth
--- FAIL: TestFleetIntegrationAnonymousAuth (4.01s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestFleetPackageNonMultiple – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestFleetPackageNonMultiple
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:132
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestFleetPackageNonMultiple
--- FAIL: TestFleetPackageNonMultiple (4.02s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestRUMRoutingIntegration – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestRUMRoutingIntegration
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				rum_test.go:201
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
        	Test:       	TestRUMRoutingIntegration
--- FAIL: TestRUMRoutingIntegration (4.59s)
 
 ```
</p></details>
</ul>
    
##### `Build and Test / System and Environment Tests / TestTailSampling – github.com/elastic/apm-server/systemtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   TestTailSampling
    kibana.go:154: 
        	Error Trace:	kibana.go:154
        	            				fleet_test.go:146
        	            				sampling_test.go:95
        	Error:      	Received unexpected error:
        	            	bad indentation of a sequence entry at line 34, column 15:
        	            	              - ""*""
        	            	                  ^
       [...]

2022-03-28 17:11 UTC, stuartnelson3 commented
@ogupte can you test this? I was able to build the package, and then run it from the local docker-compose setup, and then curl using your command [here](https://github.com/elastic/kibana/issues/121934#issuecomment-1055098129); I checked the kibana container logs and didn't see the error that was there before, but I'd appreciate your confirmation. Using the UI I was unable to add an unquoted `*` to the package, so it appears this bug only affects calls made directly to the API?

Steps within the apm-server repo:
1. `make build-package`
2. `docker-compose up -d`
3. execute schema creation command
    ```
    curl --request POST \
      --url http://localhost:5601/api/apm/fleet/apm_server_schema \
      --header 'Authorization: Basic YWRtaW46Y2hhbmdlbWU=' \
      --header 'Content-Type: application/json' \
      --header 'kbn-xsrf: true' \
      --data '{ "schema": { "apm-server.host": "0.0.0.0:8200", "apm-server.secret_token": "asdfkjhasdf", "apm-server.api_key.enabled": true, "apm-server.read_timeout": 3600, "apm-server.register.ingest.pipeline.enabled": true, "apm-server.rum.enabled": true, "apm-server.rum.allow_origins": [ "*" ], "apm-server.rum.rate_limit": 10, "apm-server.shutdown_timeout": "30s", "logging.level": "error", "logging.metrics.enabled": false, "queue.mem.events": 2000, "queue.mem.flush.min_events": 267, "queue.mem.flush.timeout": "1s", "setup.template.settings.index.auto_expand_replicas": "0-1", "setup.template.settings.index.number_of_replicas": 1, "setup.template.settings.index.number_of_shards": 1 } }'

    ```
4. check kibana container logs for `YAMLException`
    ```
    docker logs $(docker ps | grep kibana | awk '{print $1}') 2>&1 | less
    ```

Adding the double-quotes to the template didn't work because it breaks the default value -- either the default value isn't accepted if I [remove the double quotes](https://github.com/elastic/apm-server/pull/7682/commits/d6b460c89234c611d70464c6cf7f282a183a059f), or the default value has [two sets of double quotes](https://github.com/elastic/apm-server/pull/7682/commits/d6b460c89234c611d70464c6cf7f282a183a059f). I'm not really sure what to do at this point if the triple `{{{this}}}` doesn't work, but I'm having trouble re-producing the initial failure now.

2022-03-28 17:45 UTC, stuartnelson3 commented
/test

2022-03-29 01:31 UTC, ogupte commented
I don't think the triple curly braces will ensure quotes, all it will do is prevent the output from encoding certain special characters into HTML entities. 

I created a fix in the APM fleet migration logic in Kibana that will loop thru the saved text values and test whether they are valid YAML strings before wrapping them in quotes (prevents double-wrapping):  https://github.com/elastic/kibana/pull/128704

This should work as the short-term fix outlined in @joshdover's comment: https://github.com/elastic/kibana/issues/121934#issuecomment-1070834532. 

My fix however is not able to be backported as it's specific to 8.2 code refactor of the migration logic.

2022-03-29 01:32 UTC, ogupte requested changes
see https://github.com/elastic/apm-server/pull/7682#issuecomment-1081308547

2022-03-29 06:18 UTC, stuartnelson3 commented
closed in favor of https://github.com/elastic/kibana/pull/128707

2022-03-29 06:18 UTC, closed without merging