feat: rename process.ppid to process.parent.pid
elastic/apm-server pull request #8783
Opened 2022-08-02 17:50 UTC by kruskall

## Motivation/summary

ECS 8.0 removed process.ppid, which has been
replaced with process.parent.pid

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

## Related issues

Closes https://github.com/elastic/apm-server/issues/7256

2022-08-02 18:16 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8783/detail/PR-8783/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8783/detail/PR-8783/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8783/detail/PR-8783/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8783/detail/PR-8783/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_8783.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-08-02T17:40:52.698Z&rangeTo=2022-08-02T18:00:52.698Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=447ad2c1222b1598c9ba6e5065f9296b&transactionId=a78622e26fd14cda)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-02T17:50:52.698+0000


* Duration: 26 min 41 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 137  |
| Skipped      | 1 |
| Total        | 138   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-02 18:16 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                                            old time/op    new time/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
FetchAndAdd/FetchFromCache-12                                     42.6ns ± 3%    41.9ns ± 0%   -1.62%  (p=0.016 n=5+4)
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
ModelIndexer/NoCompression-12                                     1.18µs ±23%    1.05µs ± 2%  -10.97%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessorParallel/BenchmarkBackendProcessorParallel2-12    0.00ns ±32%    0.00ns ±29%  +46.58%  (p=0.032 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

name                                                            old alloc/op   new alloc/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec/1000_events-12                              3.23MB ± 0%    3.19MB ± 0%   -1.12%  (p=0.029 n=4+4)

name                                                            old allocs/op  new allocs/op  delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

```

_report generated with https://pkg.go.dev/golang.org/x/perf/cmd/benchstat_
<!--COMMENT_GENERATED_WITH_ID_bench.diff-->

2022-08-03 03:37 UTC, axw requested changes
@kruskall a few things:

- The intake API should remain unchanged, it's only the Elasticsearch document structure that should be updated. In other words, there should be no changes to `modeldecoder/v2/model.go`.
- The `process.ppid` field needs to be renamed in `apmpackage/data_stream/*/fields/ecs.yml`. I think we should probably also add an alias from `process.ppid` to `process.parent.pid`
- We will need to update our ingest pipelines to rename `process.ppid` sent by older versions of APM Server, for each of the data streams modified above.

For the last point, I suggest defining a new ingest pipeline in https://github.com/elastic/apm-server/blob/main/apmpackage/cmd/genpackage/pipelines.go, and then inserting a reference to it in each data stream's `ingest_pipeline/default.yml`.

2022-08-08 02:45 UTC, kruskall commented
> @kruskall a few things:
> 
>     * The intake API should remain unchanged, it's only the Elasticsearch document structure that should be updated. In other words, there should be no changes to `modeldecoder/v2/model.go`.
> 
>     * The `process.ppid` field needs to be renamed in `apmpackage/data_stream/*/fields/ecs.yml`. I think we should probably also add an alias from `process.ppid` to `process.parent.pid`
> 
>     * We will need to update our ingest pipelines to rename `process.ppid` sent by older versions of APM Server, for each of the data streams modified above.
> 
> 
> For the last point, I suggest defining a new ingest pipeline in https://github.com/elastic/apm-server/blob/main/apmpackage/cmd/genpackage/pipelines.go, and then inserting a reference to it in each data stream's `ingest_pipeline/default.yml`.

Thanks for the help and the explanation! 🙇 

I've updated the code!

2022-08-08 03:29 UTC, axw approved these changes
LGTM, thanks!

2022-08-08 03:52 UTC, merged