apmbench: Replace -warmup-events for -warmup-time
elastic/apm-server pull request #8855
Opened 2022-08-12 07:08 UTC by marclop

## Motivation/summary

Removes the `-warmup-events` flag and the complicated logic required to
handle timeouts it in favor of a new flag `-warmup-time` which will send
events for the specified duration. This strategy falls more in line with
the intended usage for a warmup phase, where a user wants to warm up the
target server for an amount of time using the specified agents and does
not care much about how many events are sent for that warmup phase.

Also re-formats some unformatted tf files, and adds a new make benchmark
target which auto-tunes the number of agents from the APM Server size.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
- [x] Documentation has been updated

## How to test these changes

Run `apmbench` with `-warmup-time` and see if it warms up the APM Server for the set time.

## Related issues

Part of #8775

2022-08-12 07:35 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_8855.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-08-12T06:58:49.526Z&rangeTo=2022-08-12T07:18:49.526Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=f69ba128a6336bbf55bef8a702566235&transactionId=c0cff1055eda5536)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-12T07:08:49.526+0000


* Duration: 27 min 53 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 3  |
| Passed       | 124  |
| Skipped      | 1 |
| Total        | 128   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    
    
##### `Test_warmup/1_agent_1s_events – github.com/elastic/apm-server/systemtest/benchtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   Test_warmup/1_agent_1s_events
    main_test.go:89: 
        	Error Trace:	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-8855/src/github.com/elastic/apm-server/systemtest/benchtest/main_test.go:89
        	Error:      	"0" is not greater than "1"
        	Test:       	Test_warmup/1_agent_1s_events
    --- FAIL: Test_warmup/1_agent_1s_events (1.35s)
 
 ```
</p></details>
</ul>
    
##### `Test_warmup/10_agent_1s_events – github.com/elastic/apm-server/systemtest/benchtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   Test_warmup/10_agent_1s_events
    main_test.go:89: 
        	Error Trace:	/var/lib/jenkins/workspace/pm-server_apm-server-mbp_PR-8855/src/github.com/elastic/apm-server/systemtest/benchtest/main_test.go:89
        	Error:      	"0" is not greater than "10"
        	Test:       	Test_warmup/10_agent_1s_events
    --- FAIL: Test_warmup/10_agent_1s_events (10.05s)
 
 ```
</p></details>
</ul>
    
##### `Test_warmup – github.com/elastic/apm-server/systemtest/benchtest`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Failed 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 === RUN   Test_warmup
--- FAIL: Test_warmup (11.39s)
 
 ```
</p></details>
</ul>
    
</p></details>


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8855/detail/PR-8855/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Run Linux tests`
<ul>
<li>Took 12 min 10 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-8855/runs/1/steps/344/log/?start=0">here</a></li>
<li>Description: <code>./.ci/scripts/linux-test.sh</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-12 07:35 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                                            old time/op    new time/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/nop_codec_big_tx/10_events-12                          27.1µs ±24%    20.0µs ±21%  -26.19%  (p=0.008 n=5+5)

name                                                            old alloc/op   new alloc/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

name                                                            old allocs/op  new allocs/op  delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

```

_report generated with https://pkg.go.dev/golang.org/x/perf/cmd/benchstat_
<!--COMMENT_GENERATED_WITH_ID_bench.diff-->

2022-08-14 15:57 UTC, kruskall requested changes

2022-08-14 15:57 UTC, kruskall commented on systemtest/benchtest/main_test.go
> +				}
**issue**: we should return early here. if `w.Write` is called the server has already sent a response to the client

2022-08-14 15:57 UTC, kruskall commented on systemtest/benchtest/main.go
> +			if e, ok := err.(timeoutError); ok && e.Timeout() {
**suggestion:** I think we can use `errors.As` and `net.Error` to check if `err` is a network error and then call `Timeout()` on it.
We should also add a TODO to remove this once we update to Go 1.19 as the workaround is no longer necessary: https://go.dev/doc/go1.19#net

2022-08-14 15:57 UTC, kruskall commented on systemtest/benchtest/main_test.go
> +				}
**issue:** `scanner.Err()` should be checked before returning status accepted

2022-08-15 01:57 UTC, marclop commented
@kruskall thanks for the suggestions. Addressed them in the last commit.

2022-08-15 07:29 UTC, kruskall approved these changes
LGTM!

2022-08-15 08:22 UTC, merged