Remove all uses of Python apart from Rally
elastic/apm-server pull request #8859
Opened 2022-08-14 07:04 UTC by axw

## Motivation/summary

Remove all uses of Python apart from Rally, to simplify and speed up our build, and reduce the amount of custom code we are maintaining.

`script/copy_package.py` is no longer needed, as snapshot packages are automatically published to storage. Non-snapshot packages do not need any modifications, and can be copied verbatim.

`script/copy-docs.py` is replaced with a simple `rsync` command. `make update-beats-docs` now copies from the beats module specified in go.mod.

`script/generate_notice.py` is replaced with a simpler "go list" command that is directly piped to `go-licence-detector`. I have copied the beats NOTICE.txt/dependencies.csv templates, rules, and overrides, with our modifications made directly in the templates. The order of dependencies in NOTICE.txt has changed, hence the file has been regenerated.

`script/latest_snapshot_version.py` is replaced with a simple shell script using `curl` and `jq`.

Because only Rally requires Python now, we remove `script/requirements.txt`, and the `autopep8` and `check-autopep8` Makefile targets.

## Checklist

~- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)~
~- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)~
~- [ ] Documentation has been updated~

## How to test these changes

N/A

## Related issues

None

2022-08-14 07:11 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8859/detail/PR-8859/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8859/detail/PR-8859/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8859/detail/PR-8859/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8859/detail/PR-8859/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_8859.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-08-14T06:54:45.912Z&rangeTo=2022-08-14T07:14:45.912Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=be126fbaef0fb7468adcc727e88b76a1&transactionId=e445d9e2a443353c)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-08-14T07:04:45.912+0000


* Duration: 7 min 50 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-8859/detail/PR-8859/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Run intake`
<ul>
<li>Took 3 min 55 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-server/pipelines/apm-server-mbp/pipelines/PR-8859/runs/1/steps/158/log/?start=0">here</a></li>
<li>Description: <code>./.ci/scripts/intake.sh</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-08-14 09:55 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                                            old time/op    new time/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor-12                                               0.00ns ±25%    0.00ns ±19%  -40.50%  (p=0.008 n=5+5)
RUMV3Processor-12                                                 0.00ns ±24%    0.00ns ±11%  -54.61%  (p=0.008 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec_big_tx/0_events-12                           335ns ± 6%     308ns ± 2%   -8.06%  (p=0.008 n=5+5)
ReadEvents/json_codec_big_tx/399_events-12                        3.28ms ± 0%    3.25ms ± 0%   -0.88%  (p=0.016 n=5+4)
IsTraceSampled/sampled-12                                         78.0ns ± 1%    79.0ns ± 1%   +1.22%  (p=0.040 n=5+5)
IsTraceSampled/unsampled-12                                       79.0ns ± 1%    78.2ns ± 1%   -1.06%  (p=0.048 n=5+5)

name                                                            old alloc/op   new alloc/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
ModelIndexer/BestSpeed-12                                         2.62kB ± 0%    2.74kB ± 4%   +4.46%  (p=0.048 n=5+5)
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/nop_codec/1000_events-12                               2.17MB ± 0%    2.17MB ± 0%   -0.28%  (p=0.008 n=5+5)

name                                                            old allocs/op  new allocs/op  delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/decoder goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

```

_report generated with https://pkg.go.dev/golang.org/x/perf/cmd/benchstat_
<!--COMMENT_GENERATED_WITH_ID_bench.diff-->

2022-08-14 14:31 UTC, kruskall requested changes
Great change! Just a minor issue in the shell script

2022-08-14 14:31 UTC, kruskall commented on script/latest_snapshot_version.sh
> +BRANCH=$1
**suggestion**: should we guard against `BRANCH` being empty and return an error ?

2022-08-14 14:31 UTC, kruskall commented on script/latest_snapshot_version.sh
> +curl --silent "https://snapshots.elastic.co/latest/$BRANCH.json" | jq -r .version
**issue**: curl is suppressing errors. I think we should only ignore stdout and let stderr print the errors (`jq` will fail anyway but at least we would have the error message)

Something like `curl --silent --show-error` should be okay

2022-08-14 14:31 UTC, kruskall commented on script/latest_snapshot_version.sh
> +curl --silent "https://snapshots.elastic.co/latest/$BRANCH.json" | jq -r .version
**issue**: `jq` doesn't return a proper exit code. We should use `-e` to set the exit code and try to handle empty input or missing key.

To reproduce:

```
~ % echo "" | jq -r .version
~ % echo $?
0
```

Fix attempt using `-e -n`:

```
~ % echo "" | jq -e -n -r 'input.version'
jq: error (at <stdin>:1): break
~ % echo $?
1
```

2022-08-15 00:47 UTC, axw commented
Thanks @kruskall, good catches! Updated with your suggestions.

2022-08-15 01:07 UTC, kruskall approved these changes
Thanks, LGTM!

2022-08-15 02:05 UTC, merged