poc: enable doc-value-only mappings for APM data streams
elastic/apm-server pull request #9316
Opened 2022-10-10 02:04 UTC by kruskall

## Motivation/summary

Mark `timestamp.us` as doc-value-only field for a quick poc.

Add test to verify the field is indexed as expected.

This is a PoC and `timestamp.us` is used as an example. The actual list of fields should be decided after coordinating with the UI team.

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

## Related issues

2022-10-10 02:33 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9316/detail/PR-9316/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9316/detail/PR-9316/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9316/detail/PR-9316/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9316/detail/PR-9316/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_9316.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-10-10T01:54:29.603Z&rangeTo=2022-10-10T02:14:29.603Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=f88e69031d68b1be926d40f2f347a116&transactionId=25e83f2abdfcb6d8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-10T02:04:29.603+0000


* Duration: 28 min 27 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 150  |
| Skipped      | 0 |
| Total        | 150   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-10 02:33 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                                                                              old time/op    new time/op     delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
ContextReset/X-Forwarded-For_ipv6-12                                                                 669ns ±24%      936ns ± 7%  +40.04%  (p=0.008 n=5+5)
ContextReset/X-Real-IP_ipv4-12                                                                       772ns ± 7%      900ns ±14%  +16.69%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
ModelIndexer/DefaultCompression-12                                                                  6.20µs ±16%     8.94µs ±44%  +44.16%  (p=0.032 n=5+5)
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/ratelimit.ndjson-12                                                                41.7µs ±21%     51.6µs ±15%  +23.75%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/ratelimit.ndjson-12                     19.5µs ± 8%     17.8µs ± 3%   -8.32%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/span-links.ndjson-12                    4.01µs ± 4%     4.41µs ± 9%   +9.98%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/errors_rum.ndjson-12                    2.39µs ± 1%     2.37µs ± 1%   -0.97%  (p=0.048 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/invalid-event.ndjson-12                 3.85µs ± 1%     3.80µs ± 0%   -1.26%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions_spans.ndjson-12            11.0µs ± 1%     11.2µs ± 1%   +1.49%  (p=0.016 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/invalid-metadata-2.ndjson-12           469ns ± 1%      496ns ± 1%   +5.72%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/invalid-metadata.ndjson-12             478ns ± 1%      497ns ± 1%   +3.95%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/metadata-null-values.ndjson-12         761ns ± 0%      767ns ± 1%   +0.76%  (p=0.048 n=4+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/metricsets.ndjson-12                  4.38µs ± 1%     4.43µs ± 1%   +1.25%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/minimal.ndjson-12                     1.95µs ± 2%     1.98µs ± 1%   +1.54%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/transactions_spans_rum_2.ndjson-12    1.55µs ± 1%     1.52µs ± 1%   -1.86%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
IsTraceSampled/unsampled-12                                                                         78.0ns ± 1%     76.1ns ± 1%   -2.40%  (p=0.008 n=5+5)

name                                                                                              old alloc/op   new alloc/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
ModelIndexer/DefaultCompression-12                                                                  2.63kB ± 1%     2.68kB ± 2%   +2.16%  (p=0.032 n=5+5)
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/optional-timestamps.ndjson-12                                                      4.46kB ± 2%     4.53kB ± 1%   +1.56%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/invalid-json-event.ndjson-12            4.56kB ± 2%     4.66kB ± 2%   +2.25%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/invalid-metadata-2.ndjson-12            3.24kB ± 1%     3.19kB ± 2%   -1.62%  (p=0.024 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/metadata-null-values.ndjson-12          3.69kB ± 0%     3.63kB ± 1%   -1.64%  (p=0.016 n=4+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/ratelimit.ndjson-12                     12.3kB ± 3%     12.0kB ± 2%   -2.84%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/transactions_spans.ndjson-12            25.7kB ± 1%     25.4kB ± 1%   -1.14%  (p=0.016 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/minimal.ndjson-12                     6.12kB ± 1%     6.04kB ± 1%   -1.37%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/transactions_spans_rum_2.ndjson-12    5.92kB ± 1%     6.00kB ± 1%   +1.30%  (p=0.024 n=5+5)
ReadBatch/invalid-json-event.ndjson-12                                                              3.24kB ± 0%     3.23kB ± 0%   -0.04%  (p=0.048 n=5+5)
ReadBatch/optional-timestamps.ndjson-12                                                             3.62kB ± 0%     3.62kB ± 0%   -0.09%  (p=0.016 n=5+5)
ReadBatch/transactions_spans.ndjson-12                                                              22.8kB ± 0%     22.8kB ± 0%   -0.08%  (p=0.008 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/nop_codec/199_events-12                                                                   469kB ± 0%      470kB ± 0%   +0.06%  (p=0.016 n=4+5)

name                                                                                              old allocs/op  new allocs/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

name                                                                                              old speed      new speed       delta
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/ratelimit.ndjson-12                                                               102MB/s ±18%     82MB/s ±14%  -19.45%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/ratelimit.ndjson-12                    217MB/s ± 8%    236MB/s ± 3%   +8.91%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/span-links.ndjson-12                   170MB/s ± 4%    155MB/s ± 9%   -8.85%  (p=0.032 n=5+5)
BackendProcessorParallel/Be [...]

2022-10-10 09:48 UTC, axw requested changes
I'm not convinced that the test is necessary, since it's second guessing that Fleet is working as expected. WDYT?

2022-10-10 09:48 UTC, axw commented on apmpackage/apm/data_stream/traces/manifest.yml
> +              index: false
I think we should instead update `fields/fields.yml`:

https://github.com/elastic/apm-server/blob/ff5e1792298a52fffef1e5079917942b6b364c94/apmpackage/apm/data_stream/traces/fields/fields.yml#L248-L251

IIANM you can just add `index: false` to the field definition there.

2022-10-18 14:19 UTC, kruskall commented on apmpackage/apm/data_stream/traces/manifest.yml
> +              index: false
Thanks for the tip! :bow: 

I've updated the poc to use the fields mentioned in the related issue

2022-10-18 20:42 UTC, kruskall commented
> I'm not convinced that the test is necessary, since it's second guessing that Fleet is working as expected. WDYT?

Agree, I've removed the test. I've updated the PR to use the new fields.

2022-10-19 00:50 UTC, axw commented on apmpackage/apm/data_stream/traces/manifest.yml
> +              index: false
Thanks, looks good :)

2022-10-28 03:35 UTC, axw approved these changes
Looks good!

Later on we should revisit _how_ we define the fields that should or should not be indexed. For example we might update the package generator (apmpackage/cmd/genpackage) to inject the property across all the data streams for certain fields.

That would save us from having to manually keep them in sync. Also it would enable us to define some policies, like "all metric fields should be doc-value-only". We might also want to opt into indexing, rather than opting out, depending on how many fields are actually used in searches.

2022-11-01 08:18 UTC, merged