feat: store well defined metrics as times-series data streams
elastic/apm-server pull request #9730
Opened 2022-12-02 09:10 UTC by kruskall

## Motivation/summary

## Checklist

- [ ] Update [CHANGELOG.asciidoc](https://github.com/elastic/apm-server/blob/main/CHANGELOG.asciidoc)
- [ ] Update [package changelog.yml](https://github.com/elastic/apm-server/blob/main/apmpackage/apm/changelog.yml) (only if changes to `apmpackage` have been made)
- [ ] Documentation has been updated

For functional changes, consider:
- Is it observable through the addition of either **logging** or **metrics**?
- Is its use being published in **telemetry** to enable product improvement?
- Have system tests been added to avoid regression?

## How to test these changes

## Related issues

Closes https://github.com/elastic/apm-server/issues/9649

2022-12-02 09:37 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9730/detail/PR-9730/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9730/detail/PR-9730/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9730/detail/PR-9730/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9730/detail/PR-9730/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_9730.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-12-02T09:00:33.412Z&rangeTo=2022-12-02T09:20:33.412Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=9f4d5a818adfe42a16aaa83eec5c18b4&transactionId=b0b7f34d760ad305)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-12-02T09:10:33.412+0000


* Duration: 27 min 35 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 153  |
| Skipped      | 0 |
| Total        | 153   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-12-02 09:37 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                                                                              old time/op    new time/op     delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
ContextReset/Forwarded_ipv4-12                                                                      1.03µs ±26%     0.74µs ±17%  -27.92%  (p=0.008 n=5+5)
ContextResetContentEncoding/gzip_sniff-12                                                           3.71µs ± 9%     4.11µs ± 3%  +10.80%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/minimal.ndjson-12                                                                  24.5µs ±13%     19.5µs ±25%  -20.43%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/transactions-huge_traces.ndjson-12      20.1µs ±49%     15.9µs ± 2%  -20.94%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/transactions_spans.ndjson-12            19.6µs ± 8%     20.8µs ± 6%   +6.03%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/invalid-event.ndjson-12                 3.86µs ± 0%     3.89µs ± 1%   +0.81%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions-huge_traces.ndjson-12      5.56µs ± 1%     5.61µs ± 1%   +1.00%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions.ndjson-12                  11.0µs ± 1%     10.9µs ± 1%   -1.23%  (p=0.016 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/invalid-metadata.ndjson-12             486ns ± 1%      497ns ± 2%   +2.36%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/transactions_spans.ndjson-12          9.16µs ± 1%     9.28µs ± 1%   +1.40%  (p=0.016 n=5+5)
ReadBatch/events.ndjson-12                                                                           169µs ±10%      212µs ±14%  +25.41%  (p=0.016 n=5+5)
ReadBatch/metadata-null-values.ndjson-12                                                            10.3µs ±16%     11.9µs ± 9%  +16.20%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
TraceGroups-12                                                                                       142ns ±11%      124ns ± 9%  -12.73%  (p=0.032 n=5+5)
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec/100_events-12                                                                  813µs ± 1%      798µs ± 2%   -1.84%  (p=0.016 n=5+5)
ReadEvents/nop_codec/399_events-12                                                                   418µs ± 9%      463µs ± 9%  +10.88%  (p=0.032 n=5+5)

name                                                                                              old alloc/op   new alloc/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
ModelIndexer/BestSpeed-12                                                                           2.59kB ± 0%     2.61kB ± 1%   +0.52%  (p=0.032 n=5+5)
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/events.ndjson-12                                                                   39.9kB ± 0%     40.2kB ± 1%   +0.86%  (p=0.032 n=5+5)
BackendProcessor/metricsets.ndjson-12                                                               13.4kB ± 1%     13.2kB ± 1%   -1.50%  (p=0.032 n=5+5)
BackendProcessor/span-links.ndjson-12                                                               5.00kB ± 2%     4.91kB ± 0%   -1.77%  (p=0.016 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/ratelimit.ndjson-12                     12.4kB ± 1%     12.6kB ± 1%   +1.30%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/transactions.ndjson-12                  28.2kB ± 1%     27.8kB ± 1%   -1.21%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/transactions_spans.ndjson-12            25.8kB ± 1%     25.4kB ± 1%   -1.36%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions_spans_rum.ndjson-12        6.45kB ± 1%     6.48kB ± 0%   +0.48%  (p=0.032 n=5+4)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/metadata.ndjson-12                    5.45kB ± 1%     5.40kB ± 0%   -0.96%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel200/transactions_spans_rum.ndjson-12      6.20kB ± 2%     6.32kB ± 1%   +2.10%  (p=0.016 n=5+5)
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec/1000_events-12                                                                3.49MB ± 1%     3.48MB ± 0%   -0.55%  (p=0.048 n=5+5)

name                                                                                              old allocs/op  new allocs/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64

name                                                                                              old speed      new speed       delta
pkg:github.com/elastic/apm-server/internal/model/modelindexer goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/processor/stream goos:linux goarch:amd64
BackendProcessor/minimal.ndjson-12                                                                42.6MB/s ±14%   54.1MB/s ±22%  +26.94%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel2/transactions-huge_traces.ndjson-12     166MB/s ±36%    200MB/s ± 2%  +20.38%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel4/transactions_spans.ndjson-12           297MB/s ± 8%    280MB/s ± 6%   -5.78%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/invalid-event.ndjson-12                198MB/s ± 0%    197MB/s ± 1%   -0.80%  (p=0.008 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions-huge_traces.ndjson-12     570MB/s ± 1%    565MB/s ± 1%   -0.98%  (p=0.032 n=5+5)
BackendProcessorParallel/BenchmarkBackendProcessorParallel8/transactions.ndjson-12              [...]

2022-12-05 12:44 UTC, simitt requested changes
My understanding is that the [`index_mode` needs to be set per index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-tsds.html#create-tsds-index-template), and the [fields are used to create dimensions](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-tsds.html#tsds-create-mappings-component-template). We need to look into which fields should be used for a dimension, and which metrics should have a `time_series_metric` definition. 

Other things such as [`look-ahead time`](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-look-ahead-time) might also need to be considered. 

This is supposed to be a PoC and we need to test implications on the APM UI. Did you mean to create this PR to be ready for review? I suggest to put it into draft until everything is figured out.

2022-12-05 12:54 UTC, kruskall commented
> My understanding is that the [`index_mode` needs to be set per index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-tsds.html#create-tsds-index-template), and the [fields are used to create dimensions](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-tsds.html#tsds-create-mappings-component-template). We need to look into which fields should be used for a dimension, and which metrics should have a `time_series_metric` definition.
> 
> Other things such as [`look-ahead time`](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-look-ahead-time) might also need to be considered.
> 
> This is supposed to be a PoC and we need to test implications on the APM UI. Did you mean to create this PR to be ready for review? I suggest to put it into draft until everything is figured out.

Thanks for sharing! I think I misunderstood how this should work, I'll read up more docs about it and udpate the PR

2022-12-23 14:20 UTC, simitt reviewed
@kruskall lmk once this should be reviewed again. I know that there is currently a Kibana blocker, but we also discussed focusing on the dimensions.

2023-01-17 12:37 UTC, simitt commented
@kruskall we discussed that (almost) all of the fields that are part of the transaction metrics aggregation key should be part of the dimensions. I find following fields from the key missing in this PR:

```
faasColdstart          
faasName               
hostOSPlatform         
kubernetesPodName      
cloudRegion            
cloudAvailabilityZone  
cloudAccountID         
cloudAccountName       
cloudMachineType       
cloudProjectID         
cloudProjectName       	
serviceNodeName        
transactionName        
transactionResult      
transactionType        
eventOutcome           
faasTriggerType        
hostHostname           
hostName               
containerID            
traceRoot 
```

Can you explain why you excluded these fields from the TSDB key? If in doubt, I'd start out with adding all the fields from the aggregation key to the dimensions and see if that causes any issues or performance issues. 

Since a goal of this PoC is not to merge the change to TSDB but evaluate potential issues on the UI or on performance, please update as soon as possible, so that the work on the evaluation can start.

2023-01-18 04:14 UTC, kruskall commented
> @kruskall we discussed that (almost) all of the fields that are part of the transaction metrics aggregation key should be part of the dimensions. I find following fields from the key missing in this PR:
> 
> ```
> faasColdstart          
> faasName               
> hostOSPlatform         
> kubernetesPodName      
> cloudRegion            
> cloudAvailabilityZone  
> cloudAccountID         
> cloudAccountName       
> cloudMachineType       
> cloudProjectID         
> cloudProjectName       	
> serviceNodeName        
> transactionName        
> transactionResult      
> transactionType        
> eventOutcome           
> faasTriggerType        
> hostHostname           
> hostName               
> containerID            
> traceRoot 
> ```
> 
> Can you explain why you excluded these fields from the TSDB key? If in doubt, I'd start out with adding all the fields from the aggregation key to the dimensions and see if that causes any issues or performance issues.
> 
> Since a goal of this PoC is not to merge the change to TSDB but evaluate potential issues on the UI or on performance, please update as soon as possible, so that the work on the evaluation can start.

@simitt I was trying to test the changes out progressively, unfortunately rally takes is uploading the corpora which takes an absurd amount of time on slow connections. I've added all the dimensions but I'm unable to get some numbers at the moment.

2023-02-20 12:28 UTC, simitt commented
Closing this for now until the blocker with limiting the number of dimensions is closed.

2023-02-20 12:28 UTC, closed without merging

2024-03-14 23:11 UTC, StephanErb commented
> Closing this for now until the blocker with limiting the number of dimensions is closed.

@simitt @salvatore-campagna @felixbarny  now that https://github.com/elastic/elasticsearch/issues/93564 is solved and the  TSDB dimension limit is gone, is it possible to reopen this and bring TSBD-support to APM?