ci: Move systemtests to GitHub actions
elastic/apm-server pull request #9928
Opened 2022-12-29 09:31 UTC by marclop

## Motivation/summary

Removes the system tests from Jenkins over to GitHub Actions, since they take a long time to run in Jenkins.

## Related issues

#9567

2022-12-29 09:41 UTC, apmmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9928/detail/PR-9928/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9928/detail/PR-9928/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9928/detail/PR-9928/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-server%2Fapm-server-mbp%2FPR-9928/detail/PR-9928/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-server_9928.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-12-29T09:21:29.454Z&rangeTo=2022-12-29T09:41:29.454Z&transactionName=BUILD+apm-server%2Fapm-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=7dbfa58960e048104e086de29c549e6b&transactionId=015d48ca3bea44b0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-12-29T09:31:29.454+0000


* Duration: 10 min 3 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `/package` : Generate and publish the docker images.


- `/test windows` : Build & tests on Windows.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-12-29 09:41 UTC, apmmachine commented
### :books: Go benchmark report

Diff with the `main` branch

```
name                                          old time/op    new time/op    delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec_big_tx/100_events-12       995µs ± 2%    1018µs ± 1%  +2.30%  (p=0.032 n=5+5)
IsTraceSampled/unknown-12                        385ns ± 1%     379ns ± 2%  -1.44%  (p=0.048 n=5+5)

name                                          old alloc/op   new alloc/op   delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/nop_codec/199_events-12               470kB ± 0%     471kB ± 0%  +0.13%  (p=0.032 n=5+5)
ReadEvents/nop_codec_big_tx/1000_events-12      2.18MB ± 0%    2.19MB ± 0%  +0.40%  (p=0.032 n=5+5)

name                                          old allocs/op  new allocs/op  delta
pkg:github.com/elastic/apm-server/internal/agentcfg goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/beater/request goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/internal/publish goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/spanmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/aggregation/txmetrics goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling goos:linux goarch:amd64
pkg:github.com/elastic/apm-server/x-pack/apm-server/sampling/eventstorage goos:linux goarch:amd64
ReadEvents/json_codec/399_events-12              5.90k ± 0%     5.90k ± 0%  -0.02%  (p=0.029 n=4+4)

```

_report generated with https://pkg.go.dev/golang.org/x/perf/cmd/benchstat_
<!--COMMENT_GENERATED_WITH_ID_bench.diff-->

2022-12-29 09:47 UTC, marclop commented
All the CI jobs were run in ~15m, vs ~30m before.

2022-12-29 10:01 UTC, reakaleek approved these changes
LGTM

However, I see you are omitting the junit test report. 

We have established a pattern to be able to post junit reports as github checks.

- https://github.com/elastic/gmux/blob/main/.github/workflows/test.yml
- https://github.com/elastic/gmux/blob/main/.github/workflows/test-reporter.yml
- [Example report](https://github.com/elastic/gmux/pull/14/checks?check_run_id=10180803086)

2022-12-29 10:02 UTC, carsonip approved these changes
It appears that we are removing junit reporting. Not sure how things will look when tests fail but the performance improvement over Jenkins really is good.

2022-12-29 10:32 UTC, marclop commented
@elastic/apm-server happy to spend some time looking at the Junit reports, in the past, I haven't found these that useful, and opening the `go test` output seems to provide the same value and none of the overhead and complication of JUnit. Let me know what you folks think.

2022-12-29 20:59 UTC, kruskall requested changes

2022-12-29 20:59 UTC, kruskall commented on .ci/Jenkinsfile
> -                  sh(label: 'Run Linux tests', script: './.ci/scripts/linux-test.sh')
**suggestion**: can we delete `linux-test.sh` ? Is it used anywhere ?

2022-12-30 00:43 UTC, kruskall approved these changes
LGTM!

2022-12-30 01:19 UTC, marclop commented
@reakaleek I've added the job as instructed but the report generator doesn't seem to be running. Is there any step I've missed or anything else I need to do?

2022-12-30 01:45 UTC, marclop commented
I just read that new workflows need to be in main before they run, so I'll merge this PR and check on a draft PR the results.

2022-12-30 01:56 UTC, merged

2022-12-30 06:59 UTC, reakaleek commented
> I just read that new workflows need to be in main before they run, so I'll merge this PR and check on a draft PR the results.

Yes, your are right! Sorry, I should have mentioned that before you started wondering!

2023-02-21 13:01 UTC, kruskall commented
@Mergifyio backport 8.7